### ISSUE TITLE
Adding resumability to ReactiveSocket

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket#102]
Inspiration and motivation

When ReactiveSocket is used between mobiles and servers on unreliable & slow networks, 
the cost of reestablishing subscriptions becomes very relevant.  Firstly to simplify the task for application developers dealing with failures, detecting that a temporary network blip has occurred and then cleared, then reissue subscriptions and deal with inconsistency of state.

Secondly, even when implemented correctly, this traffic could be extremely chatty and make reactive socket infeasible in cases involving large number of (rarely) updated subscriptions. It may be the case that this resubscription activity dominates both network traffic and latency.

Ideally ReactiveSocket would handle mobile temporary disconnections (e.g. mobile phone in the tube, or switching wi-fi networks). One of the proposed approaches was to handle network blips inside of a ReactiveSocket connection _without_ adding any special kind of a signal that “a device have reconnected and is trying to resume subscription bla, bla, bla”. The idea is to defer unsubscribe signals for subscriptions that have been implicitly terminated by a connection failure. For example:
- Client subscribes to topic A@100 (“topic A at sequence number 100”), provides 5 flow control credits.
- Server sends 2 messages  (A@100, A@101), which both reach client.
- Server sends one more message (A@102), which doesn't make it to the client, the connection breaks.
- ReactiveSocket swallows the failure. The application thinks everything is fine, but won't receive additional flow control tokens until the device reconnects and will receive unsubscribe event if the device fails to reconnect until a timeout fires/we run out of memory for buffering.
- Server provides 2 more messages (A@103, A@104) to the ReactiveSocket to be sent out to the client, the flow control kicks in.
- Client reconnects, asking for A@102, we ship all the buffered messages. If we happened to evict A@102 from the buffer, we would have to send unsubscribe signal to the application logic followed by subscribe to a topic A@102.

An approach where we hide failures and pretend that nothing happened for some time saves a portion of subscriptions churn and therefore a bit of resources. This might be true somewhat universally, as often applying and lifting back-pressure is _cheaper_ than dropping a subscription and reestablishing it. This is especially important when a subscription from a mobile device is backed by a large tree of backend subscriptions.

It seems wise to allow application developers an optional mechanism to be aware of the current connection state.  The UI may want to show stale subscriptions as grey or use alternative communication mechanisms, think "Send as Text Message".

**Comment by yschimke** [comment]
Strawman Design (credit @stupaq-fb)


Lack of sequence numbers in ReactiveSocket

ReactiveSocket Subscriptions, Streams and Channels  (I will refer to them collectively as “streams”) do not enforce application logic to provide or respect any sequence numbers when establishing a new subscription. The same limitation applies to the ReactiveStreams — one cannot expect every Producer to provide the ability of resuming a subscription from any provided sequence number. It means that without handling failures behind the scenes *we cannot provide any protocol for resuming ReactiveSocket stateful requests* (i.e. it must be implemented by application logic and leak into consecutive layers). Extending ReactiveStreams with a notion of sequence numbers is not a solution either, as ultimately our data stores and caching layers are unlikely to support efficient random seeks on a stream of updates.

Thoughts on granularity

Should we resume individual streams or entire connections? The granularity has a cost. No matter what resumption protocol one chooses, by information-theoretical arguments, one has to exchange amount of information that is at least linear in the number of independent streams to resume.

 Moreover, without any resumption protocol, all streams that were opened on a single DuplexConnection belong to the same network failure domain. If the resumption protocol suddenly breaks this assumption, application logic would have to deal with “partial failures”, where a non-trivial subset of streams on a single DuplexConnection have failed. It is possible that developers will chose not to handle partial failures by reestablishing only those streams that could not be resumed. If an application logic simply tears down and recreates all streams that lived on the same DuplexConnection, it effectively jeopardises all of our efforts to provide bandwidth-efficient reconnections.

Both concerns are addressed by an approach which resumes sessions at the granularity of a DuplexConnection. In this approach, the resumption protocol exchanges amount of data that is linear in the number of DuplexConnections. Also, since DuplexConnection is resumed or not atomically (we'll relax this assumption a tad to reduce amount of data to buffer), application logic doesn't need to deal with “partial failures”.

Information-theoretical argument — WTF does that mean?!

Imagine we expose to the user an information that a connection failed and provide it with en interface for resuming each stream *individually*. That is a different approach from the one described above, where we resume all streams on a single connection or none of them.

Since we allow the user to resume arbitrary subset of the streams on a single connection, the protocol must exchange enough *information* to actually communicate which subset shall be resumed. Suppose we have N streams on a connection. There are 2^N possible subsets, which means we have to exchange no less than N bits of information to communicate which subset shall be resumed. In practice, we'll likely need to exchange stream identifiers and artificial sequence numbers, so the the amount of data that needs to be exchanged on reconnection would be around 4-8 bytes times N, which is still better than any sane application-level reconnection protocol, but much worse then connection-level one.

The protocol

We will describe the resumption protocol as an extension to ReactiveSocket protocol, although it technically operates at a lower layer than the latter one. By extending the protocol, instead of layering them, we avoid adding another layer of frames.

An important concept is a Frame Number, which is an abstract sequence number that allows resynchronising stream of frames leading in one direction, after the transport session has been broken. A Frame Number's lifetime spans multiple transport sessions, and together with the direction (Client → Server or the opposite) uniquely identifies a frame within one ReactiveSocket connection.

 Frame Number of a frame is not exchanged as a part of it, but is assigned to each frame implicitly and in a consistent way by both sender and receiver. Frame Number of a frame sent in a particular direction on a given ReactiveSocket is equal to the number of frames that travelled in the direction on the socket across all transport sessions, that ever backed the socket. This definition is sound, as the underlying transport protocol guarantees in-order, exactly-once delivery of frames within one transport session.

Frames and error codes

* An additional frame is needed: RESUME, which always refers to an entire connection (StreamID = 0) and carries a Frame Number.
* An additional frame is needed: TRIM_CACHE, which always refers to an entire connection (StreamID = 0) and carries a Frame Number. The frame constitutes an optional feedback from a receiver of an unidirectional stream of frames that informs about a prefix of frames that has already been processed by the receiver, and even if the underlying transport connection breaks, will not be useful during the resumption procedure.
* An additional error code is needed: RESUMPTION_ERROR, which may only be delivered by an ERROR frame referring to an entire connection (StreamID = 0). The error communicates that resumption of a ReactiveSocket could not be carried out and the ReactiveSocket will be closed on both ends.

Protocol operations

The extension does not affect connection establishment procedure, unless a connection is to be resumed. A Server determines whether a Client wishes to establish a new connection or resume an old one, based on the type of the first frame sent on the newly opened transport session. If the first frame is of type RESUME the resumption procedure, described below, shall be executed, otherwise the behaviour of the Server is governed by “Connection Establishment” section or ReactiveSocket specification.

During the normal protocol operation, each end of a ReactiveSocket caches a suffix of frames it has sent via the underlying transport protocol. It also remembers Frame Number of each cached, sent frame and the last processed, received frame. Upon receipt of a TRIM_CACHE frame, the recipient evicts entries from the cache of sent frames in such a way, that the cache does not contain any of the frames with Frame Numbers lower of equal to the one carried in the TRIM_CACHE frame.

Each end of a ReactiveSocket retains the cache beyond a failure of the underlying transport session. When reconnecting, the Client reestablishes the transport session, but instead of sending a SETUP frame as in the original connection establishment procedure, it sends RESUME frame with the Frame Number of that last processed, received frame. After sending the frame, the Client waits until receiving the next frame from the server.

 The Server, matches a new transport session to the (see discussion below) ReactiveSocket instance. It received RESUME frame sent by the Client and based on the Frame Number X delivered in the frame performs one of the following actions.

* If X is lower than the Frame Number of the oldest cached, sent frame, the Server sends back ERROR frame with code RESUMPTION_ERROR, closes the transport session and destroys entire state for this ReactiveSocket, including the cache of sent frames. In this case too many frames, more than was stored in the cache on the sender side, were lost during transport session failure, and it's impossible to resume ReactiveSocket connection invisibly.
* Otherwise the Server sends RESUME frame to the Client with the Frame Number of the last processed, received frame. Right after (false-start-alike behaviour), the Server sends, in-order, all cached frames with Frame Number strictly greater than X. Afterwards, the Server continues normal operation as if no transport session failure happened. Cached frames with Frame Number less or equal to X can be evicted from the cache immediately.

The Client terminates the transport session and cleans up any state or cache associated with the ReactiveSocket connection upon receipt of an ERROR frame. However, if the Server successfully synchronised its outgoing stream and issued RESUME frame with Frame Number Y, the Client acts as follows (symmetrically to the Server's behaviour described above).

* If Y is lower than the Frame Number of the oldest cached, sent frame, the Client sends back ERROR frame with code RESUMPTION_ERROR, closes the transport session and destroys entire state for this ReactiveSocket, including the cache of sent frames.
* Otherwise the Client sends, in-order, all cached frames with Frame Number strictly greater than Y. Afterwards, the Client continues normal operation as if no transport session failure happened. Cached frames with Frame Number less or equal to Y can be evicted from the cache immediately.

It is easy to see that the sequences of frames sent by either end (and received by the opposite one) are the same no matter whether a transport session failed but the ReactiveSocket was successfully resumed or no transport session failure ever happened.

There is one caveat, though. Leasing, as defined by the ReactiveSocket specification, is only sound if the latency between both ends is bounded and their clocks are not drifting away. Fire-hosing a suffix of cached frames after receiving RESUME frame from the opposite end  might break lease contract. A refined protocol extension that works around this problem might on the other hand introduce a deadlock during the stream synchronisation step, as the first frame that cannot be resent due to lack of lease credits on the sender side would block resynchronisation procedure and therefore prevent any frames, including LEASE grants, from being issued.

To address the problem, we decided to reformulate lease contract in such a way that all lease expiry logic is inhibited for the whole duration of the reconnection and resumption procedure, starting from the failure of the original transport session up until the resumption procedure completes.

Implementation-dependent behaviour

The resumption protocol does not specify how the Server matches a new transport session to an existing ReactiveSocket, if the desire to resume connection is communicated by the Client that initiated the session. Actual implementation must take care of authenticating and verifying the transport session before allowing the resumption procedure to be carried out, otherwise a malicious client may steal session of another user.

 For example, matching of a new transport session to an existing ReactiveSocket instance can be performed based on TLS SessionID, after successful resumption of a previously negotiated TLS session.

Potential optimisations

In order to reduce the amount of memory Client and Server require for frame caching, we can filter out frames from the cache. For example, no REQUEST_FNF frame needs to be cached after being handed over to the transport protocol for sending.

Suppose a sender does not retain REQUEST_FNF frames in the cache, but does count them when assigning Frame Numbers to the cached frames. When it receives a RESUME frame after transport session has been reestablished, it resends back appropriate suffix of cached, sent messages and *reassigns* Frame Numbers to them. While computing Frame Number for a particular resent frame, the sender skips any frames that were not resent (because they were evicted from the cache) and therefore were not observed by the receiver.

It's less easy to see that presented approach drops only frames that have no delivery guarantees, never drops, duplicates or reorders  other frames, and preserves consistency of Frame Numbers assignment between both ends. Therefore it's correct.

Compatibility with implementations unaware of the extension

TODO: client will ignore unknown frames, server will accept a connection that starts with a different frame than SETUP

Resource usage

TODO: actual data science

A primary form of trading bandwidth for memory consumption is a TRIM_CACHE message, which may be issued arbitrary number of times (including none) in either direction.

TODO: How we will establish the right tuning values for reconnection (buffer size, disconnect duration, request-N values) based on optimising real world experience.

**Comment by tmontgomery** [comment]
A couple/few points.

1. The identification of session state is mentioned as being implementation dependent, but also being sensitive information. While this is quite sensitive potentially, the RS protocol must provide identification at its level for interoperability. So, this can not be implementation dependent. A TLS SessionID is not sufficient for this purpose. But may be part of _a_ solution for it when TLS is used. Generation of a unique token used in SETUP/RESUME is probably a simple method that can be made to work.
1. I agree on the resumption of individual streams requiring a minimum amount of state to be exchanged and therefore being quite cumbersome. A solution for resuming behavior should not scale with the number of streams if it can be avoided.
1. RS as a protocol doesn't specify DuplexConnection. Therefore, for resumption behavior, formalizing this for interoperability must be done outside of RS or inside it. Outside of RS is messy and would create a lot of coupling. Inside RS means it is in band. That seems much better to me.
1. The ideas above are good places to start, but do not encapsulate all requirements. For example, REQUEST_CHANNEL resumption. And what about timing where a stream is requested by a client, but the server is disconnected before the request arrives at the server? Is it lost? How would a client know? These can be defined without too much hassle, though.

For clarity, I think there should be __Goals__ for resumption added first. I would propose the following set:

1. Resumption is optional behavior for implementations. But highly suggested. Clients and Servers should assume NO resumption.
1. Resumption is desired to be fast and require a minimum of state to be exchanged.
1. Resumption is designed for loss of connectivity and assumes client and server state is maintained across connectivity loss. I.e. there is no assumption of loss of state by either end. This is very important as without it, all the requirements of "guaranteed messaging" come into play.
1. Resumption assumes duplicate data delivery will occur and will be filtered by client/server before being handed to applications.

Thoughts on these goals?

**Comment by tmontgomery** [comment]
Given the initial thoughts, here are some of the key points that need to be nailed down.

1. Identification of a client for resumption purposes. We should assume a client knows the server it is connecting to and the identification is really for the server to know _which_ client.
1. Identification of a position within the resumed stream(s). For de-duplication, each piece of "data" (RESPONSE or REQUEST_CHANNEL) needs to be identifiable.
1. For flow control, identification of a request within the resumed stream(s). REQUEST_N is ambiguous in terms of location. This is normally not a problem, but for resumption, it is probably necessary to be explicit to avoid overflow or underflow of buffering.
1. REQUEST_N with position information above may be a good way to explicitly garbage collect stream data from buffering on the server side (and client side for REQUEST_CHANNEL).

**Comment by tmontgomery** [comment]
WRT #83 The identification of a position within a stream can be achieved via the position within the connection. So, adding a byte-level connection-level flow control mechanic would allow for the possibility of identifying position.

**Comment by benjchristensen** [comment]
Meeting yesterday occurred on this topic involving @tmontgomery, @lehecka, @stupaq-fb, @vjn, and myself. 

Context is that there have been months of discussions, documents, proposals, etc amongst various different people around two major approaches:

- single connection-level frame buffer/log that can deliver all buffered frames after resumption
- per-stream tracking that can mark a stream as either "dirty" or "clean" and let the application decide how to deal with it

The principles behind this discussion have been:

- different use cases benefit from different approaches
- memory usage is different for each strategy and different use cases
- the more we've talked, the clearer it has become there is always an edge case
- many comparisons with MQTT/AMQP QoS levels
- would our solution work with a distributed reliable broker that "guarantees" message delivery?

Where we landed is as follows:

- the protocol should do as little as possible, just provide the communication and tracking mechanisms
- the implementation should be able to choose different strategies
- the APIs should expose signals/callbacks into the request/response handlers so that the application can make the decisions of what to do

In practice this means:

- the ReactiveSocket protocol will add frames to support resume, resume success, and resume fail
- the ReactiveSocket protocol will add support for tracking what has been sent/received to allow determining position on resumption
- the ReactiveSocket protocol will NOT assume any particular strategy
- resumption will be optional behavior enabled through the SETUP frame
- the ReactiveSocket implementations will be free to choose how they achieve resumption and are free to do this via the strategy pattern
- the ReactiveSocket APIs will need to expose to streams and channels callbacks such as:
  - disconnected
  - resumed(clean|dirty)

Expected implementation for reactivesocket-cpp looks something like:

- core implementation would support basic resumption if frames are not out of sync
- over time the core implementation could add other strategies such as log based or stream based tracking
- internally Facebook will experiment with strategy implementations
- the request/response handlers will have new callbacks added to them

Examples of how each strategy could work:

1) Sequence Only (no logs at all)

Resumption would only work if no frames were outstanding when the disconnect/reconnect occurred. The sequence numbers would have to match exactly. This would work fine when most connections are idle most of the time. 

On resumption all streams would receive `resume(dirty)` and then the application can choose to just continue, or regenerate a value and resend. 

2) Frame Log

A log of all frames would be retained that have not been acked (via keepalive). On disconnect all streams would receive a `disconnect` event. On resumption all frames would be sent. Each stream would receive a `resume(clean)`.

3) Stream Sequences

A data structure would track which streams have frames outstanding. On disconnect all streams would receive a `disconnect` event. On resumption, the connection frame sequence numbers would be compared with the data structure tracking each stream. The streams would be iterated over and receive either `resume(clean)` or `resume(dirty)` and behave accordingly. 


Iteraction models:

- fire-and-forget: no resumption support, messages are lost
- request-response: resumption support
	- responder side logic only
- request-stream: resumption support
	- responder side logic only
- request-channel: resumption support
	- both response and requester would need to perform resumption logic

**Comment by NiteshKant** [comment]
Closing this as resumability was added via #135
