### ISSUE TITLE
Simplify encoding of string fields in Frames 

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket#103]
Some suggested edits to the Protocol spec.

Relating to https://github.com/ReactiveSocket/reactivesocket-java/pull/113

I'd suggest change from "The string may or may not be null terminated." to "The string MUST NOT be null terminated."

Also @NiteshKant suggested just using UTF-8 for the mime type string, even though US-ASCII should be ok for mime-type definitions, why give errors if people want to get creative.

**Comment by yschimke** [comment]
BTW My reading of https://tools.ietf.org/html/rfc6838 (which I think is relevant) is that mime type string is extremely limited.

`restricted-name-chars  = ALPHA / DIGIT / "!" / "#" / "$" / "&" / "-" / "^" / "_"`

**Comment by tmontgomery** [comment]
@yschimke the example there is not the entire type. The RFC is the correct one and we should mention it. I don't mind restricting it. But it does mean that implementations must parse it and reject if not properly formed. i.e. a new error code and a check on SETUP.

**Comment by yschimke** [comment]
Does that change if we say something is UTF-8? There are still invalid encodings for UTF-8 e.g. 0 bytes.

What are the options here

1) strictest - validate ASCII (or UTF-8?) and mimetype matches the RFC
2) ASCII - but just carrying something that is known to be 1 byte per char
3) UTF-8 - non validated

**Comment by tmontgomery** [comment]
It really comes down to intent, I think.

The original wording with "MAY" means the fields can follow a pattern, but can also be totally up to the implementation without a validity being mandated. The "MAY" gives a preference, but not something that strict. On the other hand, the use of "MUST" mandates validity. UTF-8 is fairly easy to validate, though.

**Comment by yschimke** [comment]
The same thing applies to null termination.  MAY is friendly to a single implementor only interacting with the same platform, but awkward as soon as you cross platforms etc.  option 4) would be follow the setup directives somehow, except that a SETUP_ERROR may be generated because the server finds the setup invalid :(

**Comment by yschimke** [comment]
is SHOULD better?

**Comment by benjchristensen** [comment]
It has been changed to "... SHOULD be a UTF-8 encoded string. The string MUST NOT be null terminated."
