### ISSUE TITLE
Adjusting the keepalive rules

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket#110]
I have some theoretical concerns about the keepalive logic, maybe just me misunderstanding the spec.

1) API and multiple implementations?

> TCP half-open connections (and WebSockets) or other dead transports are detectable by lack of KEEPALIVE frames as specified under Keepalive Frame. The decision to close a connection due to inactivity is the applications choice.
> Request keepalive and timeout semantics are the responsibility of the application.

Currently in reactivesocket-java, there is nothing exposing the keepalive to the application.  So this can just be an API question. How to expose these and allow handling a delay in receiving a keepalive.

This is probably best handled by a PR for reactivesocket-java.

2) interval is very fast.

> A reasonable time interval between client KEEPALIVE frames SHOULD be 500ms.

This is very fast for any mobile client development since it effectively keeps the radio on permanently. SHOULD be might too strongly worded here.

3) behaviour with active but bursty clients.

Given an interval of 30 seconds, but with real traffic sent in both directions 10 seconds ago.  Is it actually important for the keepalive to be received.  Could the interval be since the earlier of the last frame from client or server?  This would mean keepalives are only sent when either side hasn't sent traffic since the interval.

**Comment by NiteshKant** [comment]
>>> Currently in reactivesocket-java, there is nothing exposing the keepalive to the application.

0.5.x version exposes a way to control keepalive behavior.

I agree with your points 1 and 2, can we decide on this before moving to 1.0?

\cc @benjchristensen @tmontgomery @stevegury @robertroeser

**Comment by benjchristensen** [comment]
Both points make sense, but I think it's the job of the protocol just to define the ability and frames, and up to implementations to choose and configure how to use them. For example, I expect both reactivesocket-cpp and reactivesocket-java to allow a client/server to configure the behavior. A mobile connection would have slower keepalives and timeouts than server-to-server would, for example. 

Thus, I agree with the points made here, but don't think anything needs to change about the spec.

**Comment by yschimke** [comment]
fine by me.  I'm not against leaving the default as 500ms, but in some cases that may swamp your actual traffic.

So point 1 is API related, not protocol.

Point 2 is left for now as the default suggestion, but APIs should allow this to be configured.
