### ISSUE TITLE
Eliminate request/subscription?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#111]
I have found that the distinction between `request/stream` and `request/subscription` confuses people. This has been discussed somewhat in the past (https://github.com/ReactiveSocket/reactivesocket/issues/40), but the original reason for differentiating between `request/stream` and `request/subscription` was primarily:

- clarify of intent in the client API of a finite stream versus infinite subscription
- enforcement on server of a subscription not emitting `onComplete`

There are not however any performance benefits to the distinction as there are for `request/response` vs `fire-and-forget` vs `request/stream` vs `request/channel`.

Since I end up having to constantly explain why `request/stream` and `request/subscription` exist, I think it is achieving the opposite of the intended goal and we should just eliminate `request/subscription`. The `request/stream` semantics can be used for both finite and infinite use cases and thus can serve subscriptions just by not emitting an `onComplete`.

If we drop it we can then clearly say that ReactiveSocket supports 4 interaction models without explaining the duplication of 2 of 5:

- request/response
- fire-and-forget
- request/stream
- channel

Does anyone else think it is worth simplifying the protocol and API by eliminating `request/subscription`?

**Comment by NiteshKant** [comment]
Strong 👍  for this 😄

**Comment by yschimke** [comment]
+1 

![image](https://cloud.githubusercontent.com/assets/231923/17690246/35261082-6385-11e6-99db-aa01a5dcac22.png)

**Comment by tmontgomery** [comment]
👍 I think this does make things cleaner.

**Comment by benjchristensen** [comment]
Okay, then should I submit a PR for the spec to remove `request/subscription`?

**Comment by lehecka** [comment]
I personally liked the differentiation between stream and subscription, but I don't have enough practical experience to fight for it. I am fine if we simplify the API and remove the extra code.

**Comment by benjchristensen** [comment]
@stevegury @robertroeser your thoughts?

**Comment by nickmahilani** [comment]
👍 for eliminating request/subscription. I think this will simplify the protocol.

**Comment by drewhk** [comment]
+1 from my side as well. Simplicity is desirable at the protocol level.

**Comment by benjchristensen** [comment]
Pretty strong support for this, so I'll eventually submit a PR with the changes to the spec ... unless someone wants to tackle it sooner than I can get to it. If so let me know you're doing so.

**Comment by NiteshKant** [comment]
@benjchristensen I can take this up but let me merge the PR #96 to introduce the protocol status so that we can do this on the next version.

**Comment by stevegury** [comment]
Closed per #113
