### ISSUE TITLE
WebPush Protocol using HTTP/2 Server Push

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#115]
This protocol uses HTTP/2 "synthesized GETs" and PUSH_PROMISE to push events from server to HTTP client. 

https://tools.ietf.org/html/draft-ietf-webpush-protocol-10

It comes across as rather complicated, and I find it interesting that the HTTP PUSH_PROMISE mechanism is formally being hijacked like this through synthesized GETs.

However, this may become a browser supported API: https://www.w3.org/TR/push-api/

**Comment by benjchristensen** [comment]
A possible deal breaker for many apps wishing to use this for background updates is the requirement for explicit permission: https://www.w3.org/TR/push-api/#permission

> 4.5 Permission
> 
> The term express permission refers to an act by the user, e.g. via user interface or host device platform features, via which the user approves the use of the Push API by the webapp.
> 
> 5 Security and privacy considerations
> 
> User agents must not provide Push API access to webapps without the express permission of the user. User agents must acquire consent for permission through a user interface for each call to the subscribe() method, unless a previous permission grant has been persisted, or a prearranged trust relationship applies. Permissions that are preserved beyond the current browsing session must be revocable.
>

**Comment by benjchristensen** [comment]
I'm interested in others take on this, particularly the use of POST, DELETE, PUSH_PROMISE, synthesized GETs, etc.

**Comment by yschimke** [comment]
It looks awfully chatty overall, so probably a bad choice for a mobile app or server-server to use.  But the design probably makes it safer for web browsers, fit with existing control mechanisms (CORS etc).  

Overall if it becomes widely supported it looks useful to support it (in addition to other optimised routes) as its likely to work through corporate proxies/firewalls and in the highest percentage of modern browsers.

**Comment by benjchristensen** [comment]
Agreed. But what's your take on the permission requirement? It seems the browser must pop up something for a user to approve. If they don't approve it then it won't work. 

It seems similar to what I've seen on sites wanting to send me Safari push notifications (https://developer.apple.com/notifications/safari-push-notifications/). I have almost always have said "no". Once a user says no, we would have no choice but to use some other solution in the background for use cases that are about pushing data updates, not showing notifications.

**Comment by yschimke** [comment]
As a user of the web I think I like it.  If it adds a bit of friction to the 63 different trackers, beacons and things running on every newspaper site, I'm for it.

As a developer of a high value site that everyone would want more updates from :), it seems unfortunate.  I guess the challenge here is to make it clear why people would want this to be active.

But my thoughts here are high on opinion, and low on deep technical analysis at the moment.

**Comment by benjchristensen** [comment]
Agreed as a user for visible push notifications. My issue though is that this seems to limit its use to that as it would be a non-trivial percent of people who say 'no' and thus it would break an app that needs push for correctness. 

I don't think we can use it for non-optional behavior if permission gets denied easily because people associate the prompt with visible and noisy notifications, which isn't what all push behavior is used for.

**Comment by NiteshKant** [comment]
This looks pretty complex to me with the introduction of the push service entity and using different HTTP GET/POST requests to subscribe/push/cancel subscriptions, especially when it is supposed to work over HTTP/2. IMO, it does more than what is required. 
If this wasn't intruding on the server side implementation (push service and application as separate entities impacting the design), it may have been much powerful as a standard.

Agree with @benjchristensen that the need for explicit user permissions makes this less useful only for specific usecases which require more user interaction (accepting a call vs updates to a social media feed).

From the perspective of ReactiveSocket, I am not sure which parts would be useful as it is way too different than a stateful single stream interaction that ReactiveSocket provides.

**Comment by wenbozhu** [comment]
Agreed. Esp. if web-push follows the http/2 spec, "pushed responses are always associated with an explicit request from the client", then the push protocol is semantically as stateful as a single "hanging GET" transaction. 

Conceptually, a push notification can be seen as a response to a polling request for monitoring state changes of an entity. I.e. it's not entirely a hijacking for browsers to use push-promises to expose a notification service. Wire efficiency is certainly not the goal.

**Comment by benjchristensen** [comment]
Closing out. Thanks for the discussion everyone.
