### ISSUE TITLE
Fragmentation/Reassembly in ReactiveSocket

### ISSUE THREAD

**Issue by vjn** [ReactiveSocket/reactivesocket#118]
(Discussed with @benjchristensen, filing for possible discussion/consideration).

The fragmentation and reassembly concern seems better relegated to a layer below ReactiveSocket: this is an application-layer protocol, and fragmentation/reassembly seems more like a transport-level function. Practically, this would mean that this functionality would become the responsibility of the various DuplexConnection implementations, and disappear from the protocol.

**Comment by tmontgomery** [comment]
Pushing Fragmentation/Reassembly down into the DuplexConnection opens the door for head of line blocking on long messages. Fragmentation is an inherent part of allowing the protocol to prevent (or at least account for the possibility of) head of line blocking at the protocol level.

**Comment by yschimke** [comment]
The protocol docs already have the follow flag e.g. for Responses.  If we remove this we generally remove the ability for a specific implementation to support streaming responses (java.io.OutputStream etc) without making it an application level concern.

**Comment by NiteshKant** [comment]
@vjn are you suggesting that the fragmentation/reassembly would be defined in a lower layer protocol (http/2, websocket, etc.) so it isn't required by ReactiveSocket? 

In absence of the fragmentation flag in the frame, it wouldn't be possible to reassemble, isn't?

**Comment by vjn** [comment]
@NiteshKant, yes, that is what I had in mind: that this is a lower-level concern. However, I do note that AMQP (for instance) also elevates fragmentation/reassembly to the message transport level of the protocol. @tmontgomery's point is regarding head-of-line blocking. I understand that; in that case, do we expect users to break up all messages into manageable-sized fragments, or use up to the 2G maximum size? If they can use such large frames, won't even a single frame cause HOL blocking? And multiple such fragments of a giant message swamp the endpoints?

**Comment by NiteshKant** [comment]
@vjn fragmentation/reassembly only applies when using `ReactiveSocket` over non-framed protocols like TCP, so yes you are correct that with HTTP/2, WebSocket, it isn't required but can not be completely removed.

IMO, HOL blocking in the scenario you have mentioned can only be removed by having stream priorities (assuming only always request-1 per stream is not a viable solution) but I am interested in hearing what @tmontgomery thinks about it.

**Comment by yschimke** [comment]
I might end up leaving this discussion with a new mental model, how would you both consider a streamed response over a framed protocol.  e.g. I'm about to generate 20mb JSON document and I can easily stream it to the other process, using the fragmentation flag to define that these individual frames should be reconstituted into a single response in requestResponse or one fo the responses in a stream.

Specifically given support in ReactiveSocket for streaming of reassembled responses, the receiving end can start processing the response before the sender finishes.

**Comment by NiteshKant** [comment]
@yschimke Making it possible for a receiver to start processing a response in chunks is contradictory to fragmentation. Typically, if you have fragmented frames, `ReactiveSocket` implementation would reassemble the frames before it emits them. So, fragmentation and reassembly is really an implementation detail and not something that gets exposed to the user of the API.

I think what you are trying to achieve is better suited with request-stream containing a single response. If it contains multiple responses, it will become an application level concern to delimit one response (over multiple frames) from another.

**Comment by yschimke** [comment]
> Typically, if you have fragmented frames, ReactiveSocket implementation would reassemble the frames before it emits them.

I think I'm biased by prior experience with HTTP frameworks instead of ReactiveStreams, so I'm happy to assume if this was a common problem that it would be part of the APIs.

**Comment by benjchristensen** [comment]
Agreed with @NiteshKant regarding the exposure to application level. If that is wanted then the app has to do the chunking itself which would work well on top of the request-stream ReactiveSocket model.

**Comment by vjn** [comment]
Closing this, based on recent discussion. Thanks.
