### ISSUE TITLE
Feedback & questions for reactive sockets (RS)

### ISSUE THREAD

**Issue by wenbozhu** [ReactiveSocket/reactivesocket#119]
Background: [bidiweb](https://github.com/bidiweb) faces similar problems and shares some similar goals with RS. There have already been some [joint discussions ](https://github.com/bidiweb/wish/issues) on HTTP/2 framing etc.
# 

API concerns (Reactive Streams)

Has there been any serious discussion on why [whatwg streams](https://github.com/whatwg/streams) doesn’t adopt the reactive-stream spec? With the JDK-9 HTTP client API adopting the Flow API, it seems we should push the web platform to adopt the same spec. Or if there are any technical gaps, it would be great to identify them now. JS-Java transcompile on Mobile could definitely benefit from a common API model wrt streaming & pushbacks. 

Related, I posted a [survey ](https://java.net/projects/servlet-spec/lists/jsr369-experts/archive/2015-10/message/0) on different flow-control models (for the servlet API) 

Has there been any discussion to support batched delivery, mostly an API concern?
# 

Transport-level flow-control

While end-to-end app-level flow-control is much more effective, I wonder if transport-level flow-control can be completely hidden from applications. E.g. how to signal to the application the process memory or local buffer is full due to slow network or peers, In other words, how to respond to local flow-control conditions.

Q: to minimize latency, is the requester supposed to send request-n frame before the requester has received all the n frames from a previous request-n request?
# 

Multiplexing (over TCP)

In light of what HTTP/2 does, that it multiplexes (interleaved) multiple byte-stream sessions over a single TCP connection, I wish there is a better term to describe “TCP connection reuse” in RS. E.g. WebSocket is not a multiplexed transport but RS is able to reuse the same WebSocket to transmit multiple request/response streams concurrently.

Multiplexing over TCP hurts performance when concurrent connection sharing is rare at the message level or at the stream level, e.g. framing overhead, CPU cache miss, 

Multiplexing over TCP (the HTTP/2 scenario) works the best for the Web, i.e. browsers (cross-tab sharing) and CDN (resource and memory/port constrained). 
# 

Ack & commit semantics

RPC offers explicit ack/commit semantics as the requester is certain that, when a response is received, the request has been delivered to the end-application.  

Has there been any discussion to support explicit ack/commit for a bidi channel?

The ack support is also useful for monitoring delivery latency. And it’s even possible to implement an in-band NTP over an ack protocol.

The commit semantics offers more or less a snapshot operation. 

It seems it’s relatively easy to support an ack/commit protocol using RS extensions.

A related [proposal ](https://github.com/bidiweb/webchannel/blob/master/commit.md) in bidiweb.

API support is also required. 
# 

Long-lived streams

Is there any written proposal to support resumable streams (session continuation?) due to failed TCP connections, e.g. due to proxy failures or network handoff? 

An ack protocol can also be used to recover from a failed TCP connection, i.e. messages to buffer and resend.

Related, is stickiness support (address or hash) to be provided by the transport (e.g. HTTP headers)?
# 

Framing 

Compression (possibly cross-message) is not discussed, or left to Transports?

I really like the metadata part. What’s the API for delivering metadata?

Layered framing (again):

It seems that the core RS framing can be kept minimum with just the optional frame length, metadata support, and frame types (globally registered), plus maybe a protocol id field. 

Not sure about stream id. Related to keep-alive, I wonder if RS needs support process-level/connection-level control messages too. If so, stream id will be optional.

Then well-known frame types (control messages) can use any structured data formats (e.g. CBOR) or any specially defined c-structs (as what RS uses now).

Such a framing can be adopted by future protocols such as WebSocket. For WebChannel, I think the core framing has everything I need too. If CBOR is indeed the best option for both control and metadata messages, protocol extension can greatly simplified. And the core framing can be optimized by proxies or at any transport binding layer.

**Comment by NiteshKant** [comment]
@wenbozhu welcome to the world of ReactiveSocket 😄 

>> Has there been any discussion to support batched delivery, mostly an API concern?

Usually, applications will use a function composition library (eg: RxJava, reactor, etc.) over `ReactiveStreams` API exposed by `ReactiveSocket`. Such a library comes with functions like `window` that facilitates batching.

>> how to respond to local flow-control conditions.

Our java implementation mediates between transport and application level flow control as the transport libraries we use (netty and aeron) supports backpressure. So, local flow-control conditions are tied to application level flow control. 
For writes, lack of `requestN`s will either indicate transport flow control or application flow control. The source of data does not care about discriminating between them but the transport implementation does the correct thing.
For reads, lack of `onNext`s can indicate slow peer or slow transport. A receiver of data incorporates timeouts/cancellations to bail out of such situations if required.

>> Q: to minimize latency, is the requester supposed to send request-n frame before the requester has received all the n frames from a previous request-n request?

According to `ReactiveStreams`, `requestN` and `onNext()` do not need to be sequential i.e. you do not need to receive all n items before you can request more. Same is true for `ReactiveSocket`. A receiver can determine when it is ready to receive more items and the source accumulates all `requestN`s.

>> Multiplexing (over TCP)

I did not completely understand the point here. `ReactiveSocket` provides multiplexing which as a feature may overlap with some protocols like HTTP/2 and not for other protocols like WebSocket. 

>> Ack & commit semantics

This is a good topic and may be better to discuss in a separate issue. There hasn't been an __official/public__ discussion on this yet and I am eager to hear the views of others.

>> The ack support is also useful for monitoring delivery latency. And it’s even possible to implement an in-band NTP over an ack protocol.

[KeepAlive frames](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#keepalive-frame) and their ack, do achieve something similar.

>> Long-lived streams

I would let @benjchristensen , @tmontgomery , @yschimke and other friends from facebook answer this as they have been working on it.

>> Compression (possibly cross-message) is not discussed, or left to Transports?

My understanding is that it is left to the transport.

>> What’s the API for delivering metadata?

It's a part of most of the frames. In java, we have a [`Payload` interface](https://github.com/ReactiveSocket/reactivesocket-java/blob/master/reactivesocket-core/src/main/java/io/reactivesocket/Payload.java) that gives access to metadata and data.

>> Layered framing (again):

I agree with the benefit of layered framing. In previous discussions, I remember @tmontgomery suggested something similar. Again, good to discuss separately IMO.

**Comment by benjchristensen** [comment]
> Has there been any serious discussion on why whatwg streams doesn’t adopt the reactive-stream spec?

Not that I've been involved in. Perhaps @viktorklang or @ktoso has been involved and has further insight?

@wenbozhu Do you think there is a reasonable approach to engaging on that topic? What do you suggest?

**Comment by benjchristensen** [comment]
> While end-to-end app-level flow-control is much more effective, I wonder if transport-level flow-control can be completely hidden from applications. E.g. how to signal to the application the process memory or local buffer is full due to slow network or peers, In other words, how to respond to local flow-control conditions.

I don't know. Thus far our approach has been to keep the transport byte-level flow control hidden, mostly because practically speaking it's non-trivial to reliably have access to that layer as specifications and implementations generally do not expose it. For example, HTTP/2 WINDOW_UPDATE semantics are not exposed to the application layer, and certainly not information about buffers. 

Are you thinking that you would like to have APIs specified for the transport to signal backpressure (which is how it works in APIs that do support this, such as Netty and Aeron)? Or that you want the transport to expose credit-based APIs like WINDOW_UPDATE for the application to control bytes similar to how ReactiveSocket exposes request-n?

> Q: to minimize latency, is the requester supposed to send request-n frame before the requester has received all the n frames from a previous request-n request?

Yes, the requester should send the request-n frames whenever the application requests them, not after waiting until all previously requested have been sent. Typically in a streaming scenario a requester would request more elements after some threshold has been hit, such as 2/3s have requested have been fulfilled. (It's not efficient for the requested to degenerate into just sending `request(1)` every time it receives something)

**Comment by benjchristensen** [comment]
> Multiplexing over TCP

Similar to @NiteshKant I don't fully understand the question here. I'll ask some followups on the two bullets:

> Multiplexing over TCP hurts performance when concurrent connection sharing is rare at the message level or at the stream level, e.g. framing overhead, CPU cache miss,

Having multiple ReactiveSockets layered on a single TCP connection can be less-than-ideal. The concern I would have is that they are competing for the same underlying byte streams and can cause head-of-line blocking for each other, since there is no flow control between streams at the TCP level. 

What framing overhead are you referring to? And how would this cause CPU cache misses?

There are times when we are pursuing this strategy though in server-to-server connections. We have m-to-n physical TCP connections between servers, and then far more ReactiveSocket connections layered over those TCP connections. In this use case, the traffic per ReactiveSocket (each representing a user as opposed to physical server) is small, and message size is small, so we're not concerned with HOL blocking. 

> Multiplexing over TCP (the HTTP/2 scenario) works the best for the Web, i.e. browsers (cross-tab sharing) and CDN (resource and memory/port constrained).

We have chosen to target HTTP/2 streams for multiplexing web connections (mobile and eventually browser). For browser it's out of necessity, the browser does connection management for us. For mobile it's because we have multiple data flows over a single mobile connection which routes through a single cell tower buffer anyways, and we want the HTTP/2 stream multiplexing to ensure that ReactiveSocket on one stream, and HTTP GETs of images, videos, HTML, etc on other streams are properly interleaved. TCP doesn't do that for us, and having multiple TCP connections on a constrained pipe also fight with each other (theoretically ... much harder to prove in real-world I have learned). I'd appreciate guidance and learnings from your side on this if you can share?

**Comment by benjchristensen** [comment]
> Has there been any discussion to support explicit ack/commit for a bidi channel?

Not really. We have thus far not wanted that extra traffic for streams. I think @tmontgomery is better suited to answering this question though.

We are actively pursuing a "resumability" solution that we would use instead of acking all messages. Discussions thus far involve having requester/responder sequence numbers, logs, and resume negotiation. A post on that should come soon.

**Comment by benjchristensen** [comment]
> Long-lived streams

> Is there any written proposal to support resumable streams (session continuation?) due to failed TCP connections, e.g. due to proxy failures or network handoff?

We are building that right now at Facebook as our mobile-to-server use cases are mostly long lived subscriptions. An open question is whether it should be part of ReactiveSocket (the original assumption), or a layer underneath ReactiveSocket (a recent discussion point). I will have someone post the current state of the thinking later this week I hope. 

> Related, is stickiness support (address or hash) to be provided by the transport (e.g. HTTP headers)?

Yes, we leverage our transport to provide stickiness. We have implemented this at Facebook via HTTP/2 streams which is the transport we are using from device to edge to server.

**Comment by benjchristensen** [comment]
> Compression (possibly cross-message) is not discussed, or left to Transports?

I think @tmontgomery is best suited to answering this.

**Comment by benjchristensen** [comment]
> I really like the metadata part. What’s the API for delivering metadata?

We treat Data and Metadata the same in the API. A separate mime-type is negotiated for each, and then the API allows the Frame to be populated with both Data and Metadata. The intent is that typically the Data payload is left to the application to choose, and the Metadata mime-type and payload is left to the infrastructure to choose. The goal was that infra could interpret and use metadata, but leave the data payload opaque and never touch it. 

In Java:

- the flyweight for reading metadata from a Frame: https://github.com/ReactiveSocket/reactivesocket-java/blob/master/reactivesocket-core/src/main/java/io/reactivesocket/Frame.java#L100
- a Payload interface with both Data and Metadata: https://github.com/ReactiveSocket/reactivesocket-java/blob/master/reactivesocket-core/src/main/java/io/reactivesocket/Payload.java
- RequestHandler receiving Payload types which have Data and Metadata: https://github.com/ReactiveSocket/reactivesocket-java/blob/master/reactivesocket-core/src/main/java/io/reactivesocket/RequestHandler.java#L40

**Comment by benjchristensen** [comment]
> Layered framing (again):

> It seems that the core RS framing can be kept minimum with just the optional frame length, metadata support, and frame types (globally registered), plus maybe a protocol id field.

This same thinking has been happening inside Facebook as we've been working with ReactiveSocket. I think it's a good discussion to have amongst us all. @tmontgomery is the best to lead this discussion. /cc @stevegury @NiteshKant 

Just yesterday in a meeting we were contemplating 3 layers: (1) framing, (2) optional resumability, (3) interaction models (the API parts), all as part of the resumability discussion as a way to simplify the design and execution of that use case.

**Comment by viktorklang** [comment]
@benjchristensen TBH I haven't seen the whatwg streams until now so I frankly don't know. But from looking at their spec site, it looks slightly more complicated than reactive-streams.
Does anyone here know anyone there?

**Comment by benjchristensen** [comment]
@viktorklang agreed on the complexity. @wenbozhu do you know anyone working on that spec?

**Comment by wenbozhu** [comment]
@tyoshino is actively working on whatwg streams.  Will file a new issue to collect his inputs.

**Comment by wenbozhu** [comment]
@NiteshKant  Re: batching: I think batching may need be a concept supported by the RS API, for better performance. A batched delivery saves a lot more than a "single framing", or batching is lesser a concern for a high-level API IMO.

**Comment by wenbozhu** [comment]
Re: transport-level flow-control. I am new to reactive-streams, Given that there is no send(T) defined for the publisher API, I think it's OK to consider transport-level flow-control an implementation detail. The doc could be improved though to mention that transport-level control is to be respected at the same time.

p.s. what's the typical pattern to write flow-control enabled send() in a publisher?

**Comment by benjchristensen** [comment]
>  I think it's OK to consider transport-level flow-control an implementation detail. 

Good.

> The doc could be improved though to mention that transport-level control is to be respected at the same time.

Do you mean the Protocol specification doc? If so, that's good feedback of something to make clear. 

> p.s. what's the typical pattern to write flow-control enabled send() in a publisher?

Instead of writing directly via a `send(data)` method, to submit a `Publisher` to be consumed: `send(Publisher)`.

**Comment by benjchristensen** [comment]
> p.s. what's the typical pattern to write flow-control enabled send() in a publisher?

For example:

https://github.com/ReactiveSocket/reactivesocket-java/blob/4169902707801e87f411ad235f4c137f6ccfb35b/reactivesocket-core/src/main/java/io/reactivesocket/DuplexConnection.java#L29

**Comment by benjchristensen** [comment]
> @tyoshino is actively working on whatwg streams. Will file a new issue to collect his inputs.

Thank you!

**Comment by wenbozhu** [comment]
Clarification wrt multiplexing:

My initial comment is partly on documentation.

To me, a) multiplexing: interleaved messages from concurrent transactions. I.e. messages are segmented as in the HTTP/2 case, effectively a new transport; b) connection reuse: similar to http/1.1 keep-alive, http/1.1 pipeline, and interleaved streams in RS over TCP where messages are not segmented. 

b) could be referred to something else (that is not multiplexing).

In server-to-server situation, b) will perform OK as HOL blocking is rare; and throughput is often more important.

Over the internet, a) is useful as messages can be too large (images) and network (cellular) is much slower.  Multiple TCP connections v.s. a single TCP connection probably needs a separate discussion, e.g. TCP slow-start, handshake cost, server-side (CDN) resource overhead, cross-process connection sharing (only possible on browsers?). 

Not sure if this [study](http://conferences.sigcomm.org/co-next/2013/program/p303.pdf) is still relevant.

**Comment by wenbozhu** [comment]
Re: acks. It would be something like last-message-id-received, v.s. a noop ack response for each message. My experience is that resumability could use an ack protocol (whose semantics is more generic).

Let's have a separate issue to discuss.

**Comment by wenbozhu** [comment]
> Just yesterday in a meeting we were contemplating 3 layers: (1) framing, (2) optional resumability, (3) interaction models (the API parts), all as part of the resumability discussion as a way to simplify the design and execution of that use case.

This is plausible. E.g. webchannel emulates a stateful long-lived stream over stateless RPC (over HTTP); and 2) may also support muti-homed end-points.  3) can be extended to support things like richer semantics such as commit/ack for certain applications.

**Comment by wenbozhu** [comment]
> Do you mean the Protocol specification doc? If so, that's good feedback of something to make clear.

Yes, the [spec doc](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md)

**Comment by benjchristensen** [comment]
I opened https://github.com/ReactiveSocket/reactivesocket/issues/123 to address the clarification about the transport layer being respected.

**Comment by benjchristensen** [comment]
> contemplating 3 layers

As I just commented in https://github.com/ReactiveSocket/reactivesocket/issues/123, further discussions led us away from this as it seemed like it would just complicate things and not actually achieve simplicity and reuse. Specifically we found that the layers would have leaky abstractions as we found that resumability would work best if signals into the application layer existed, which meant it couldn't be abstracted into a clean layer underneath the APIs. 

As for the framing layer, it didn't seem like a strong enough reason to separate out, especially since ReactiveSocket already supports being layered on both framed and unframed transports since the ReactiveSocket header makes length optional.

**Comment by benjchristensen** [comment]
Regarding acks and resumability, @tmontgomery should shortly be submitting a proposal for updating the spec. 

I captured the current thinking for resumability here: https://github.com/ReactiveSocket/reactivesocket/issues/102#issuecomment-255485909

**Comment by benjchristensen** [comment]
Regarding https://github.com/ReactiveSocket/reactivesocket/issues/119#issuecomment-255907053, I think I've lost the goal of the discussion about multiplexing. Can you open a separate issue to discuss that topic and provide your suggestion?

**Comment by wenbozhu** [comment]
Filed #125 for clarification about multiplexing.

Feel free to close this issue.

**Comment by benjchristensen** [comment]
Closing out as we moved specific topics to different issues.
