### ISSUE TITLE
Should Lease contains a deadline?

### ISSUE THREAD

**Issue by stevegury** [ReactiveSocket/reactivesocket#12]
We had this discussion with @NiteshKant.
The question is should the lease contains the duration/deadline or not, knowing that a server can overwrite his previous Lease with a new one.

It's a tricky question, the problem with the deadline is that the propagation delay between the server and the client makes the deadline very imprecise. This leads to recommendation about having the window >> network latency.

On the other end, an overloaded server should need to do anything to implicitely reduce the flow of incoming requests. Then just leting the lease expire, is the perfect solution.

I tend to prefer the solution with the duration, but I can be convinced.

**Comment by NiteshKant** [comment]
Absolutely it is a tricky decision to make!

My reservations around using deadline are the following:

* As you specified, using time means that we need to take care of propagation delays. 
* The client code becomes complex as it has to be considerate of time before making a request. So, it will manifest in two ways:
    * Check for current time and hence deadline before each request.
    * Or have a scheduled timer for each connection from the client that resets the request quota for that duration.

Both of the above sounds too heavy a burden to force from the protocol IMO.

I do agree that the lease expiry is a nice side-effect for an overloaded server. An argument against that could be that for a well behaved client and properly implemented flow control from the server, hitting the wall (overloaded) would mean that the server over-subscribed for requests.

Overall, I do not have a concrete reason for either ways but using time does make me nervous!

**Comment by stevegury** [comment]
Just for the record, we ended up choosing to keep a TTL in the lease message.
It has the nice property of automatically applying backpressure when a server is overloaded (it doesn't need to do any extra work to shed load away)
