### ISSUE TITLE
Clarify Role of Transport Layer

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#123]
As per discussion in https://github.com/ReactiveSocket/reactivesocket/issues/119#issuecomment-255913582, let's clarify in the spec that the transport layer must be respected:

Comment from: https://github.com/ReactiveSocket/reactivesocket/issues/119#issuecomment-255902289

> Re: transport-level flow-control. I am new to reactive-streams, Given that there is no send(T) defined for the publisher API, I think it's OK to consider transport-level flow-control an implementation detail. The doc could be improved though to mention that transport-level control is to be respected at the same time.

**Comment by benjchristensen** [comment]
Transport behavior and requirements have been clarified in the protocol: https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#transport-protocol

@tmontgomery Do we need any further clarification of transport-level flow control?

**Comment by wenbozhu** [comment]
FYI ... Mike from Microsoft and I did some similar work to document HTTP (as a REST protocol)'s dependencies on transports (i.e. tcp as http/1.1, spdy, quic, http/2, ...).

https://github.com/MikeBishop/http-layering  (there are still pending issues)

We missed FCS, which is useful to mention.

**Comment by tmontgomery** [comment]
I think we should leave this open and less proscriptive. At least at the moment.

**Comment by benjchristensen** [comment]
@tmontgomery are you suggesting we close this and leave it as is?

@wenbozhu are you saying we need to provide more clarity in the spec? If so, what do you suggest?

**Comment by tmontgomery** [comment]
I would leave as is. Or if we add some text, be very open with it so that we don't exclude too much at this point in time.

**Comment by wenbozhu** [comment]
The current text looks good. Flow control is optional, e.g. websockt, being a L7 over TCP, doesn't provide flow-control in itself.

**Comment by benjchristensen** [comment]
Closing out as we don't have anything actionable to do here.
