### ISSUE TITLE
Documentation: clarification about multiplexing

### ISSUE THREAD

**Issue by wenbozhu** [ReactiveSocket/reactivesocket#125]
Related to the [motivation doc](https://github.com/ReactiveSocket/reactivesocket/blob/master/Motivations.md)

Two separate concerns:

(1) Multiplexing bytestreams (on which messages are framed) over a byte-stream transport (i.e. TCP)

(2) Multiplexing concurrent transactions (streams) over a single TCP connection

(1) is what HTTP/2 does, and messages are fragmented arbitrarily within a single stream.  

(2) is what RS does over TCP. A different/better term for 2) would be connection reuse.

Over the internet, 1) is useful as messages can be too large (images) or network (cellular) is slower. 

In server-to-server situation, 2) will perform OK as HOL blocking is rare; and throughput is often more important.

===

Multiple TCP connections v.s. a single TCP connection probably needs a separate discussion, e.g. TCP slow-start, handshake cost, server-side (CDN) resource overhead, cross-process connection sharing (chrome tabs) ...

[Related study](http://conferences.sigcomm.org/co-next/2013/program/p303.pdf).

**Comment by benjchristensen** [comment]
I'm not understanding how what RS does is different than what HTTP/2 does. In both cases, messages can be fragmented arbitrarily on the byte stream of the TCP connection. 

The RS protocol supports fragmentation of message frames for this very reason.

**Comment by wenbozhu** [comment]
I missed the fragmentation support in RS.  This is another thing that could be moved to a lower layer.

**Comment by benjchristensen** [comment]
@tmontgomery Thoughts on that? I find that more challenging as it is now a single bit.

**Comment by wenbozhu** [comment]
somewhat related, stream priority
