### ISSUE TITLE
Pull RequestN Clarifications Into Master Branch

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#136]
https://github.com/ReactiveSocket/reactivesocket/commit/767d8fee89db90afeb7a328bf8a520e5d13983fb was merged into 0.2, but we're editing the master branch, so need to pull those in.

**Comment by NiteshKant** [comment]
I have cherry-picked the commit (resolved conflicts) into master: 
https://github.com/ReactiveSocket/reactivesocket/commit/aaf24bc32e2c872e9574746c62dc047d00c4f4a5

Appreciate a review if I messed up something in the conflict resolution.
