### ISSUE TITLE
Duplex interaction in a stream

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#14]
I think it is somewhat implicit that on a stream either the requester or the responder can send DATA,  REQUEST_N, CANCEL and other frames for a true full duplex interaction per stream but is not obvious, specially for someone coming from a ReactiveStreams/ RxJava background as the streams there are unidirectional i.e. only the producer sends `onNext`, `onComplete`, `onError` and the subscriber sends `requestN`. 

I think it will help to clarify typical interactions in various request types. Also, this can be a good place to define what is illegal in any interaction.

**Comment by tmontgomery** [comment]
I think the sections covering sequences spell this out clearly. What is missing there?

In terms of legal/illegal, we still need to spell out what is the reaction to unexpected frames. Ignore? Close Stream? send RST equivalent? close connection?

**Comment by NiteshKant** [comment]
This was my incorrect assumption that data can flow either ways in a stream. In offline discussions, it was clarified that wasn't the case. For the usecases where data should flow in either directions, there should be two streams initiated between the peers.
