### ISSUE TITLE
Rename `CONNECTION_ERROR_NO_RETRY` to `RESUME_FAILED_NO_RETRY`?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#147]
Continuing discussion from [here](https://github.com/ReactiveSocket/reactivesocket/pull/135#discussion_r94721508)

`CONNECTION_ERROR_NO_RETRY` was added for resumability and following is the description:

```
 __CONNECTION_ERROR_NO_RETRY__  | 0x00000102 | The connection is being terminated. May __NOT__ be resumed. Stream ID MUST be 0.
```

It looks like the intention is to indicate that resumption must not be attempted. So, should we rename this error code to `RESUME_FAILED_NO_RETRY`?

`CONNECTION_ERROR_NO_RETRY` sounds ambiguous as it does not indicate anything about resumability.

**Comment by benjchristensen** [comment]
The spec currently has this:

> On receiving an ERROR frame, the client MUST NOT attempt resumption again if the error code was CONNECTION_ERROR_NO_RETRY.

It also allows the server to use that error at any time it wishes to error a connection and tell the client to not attempt to retry. 

This seems generic and not just "RESUME_FAILED".

**Comment by NiteshKant** [comment]
A retry here means to not connect to that server again?

**Comment by benjchristensen** [comment]
The spec says:

> The connection is being terminated. May NOT be resumed. Stream ID MUST be 0.

So it means it can't be resumed. So perhaps one of the following clarifications is needed?

If it stays CONNECTION_ERROR_NO_RETRY change "May NOT be resumed." to "May NOT be retry against this server."

If we keep the wording "May NOT be resumed." then maybe change to CONNECTION_ERROR_NO_RESUME?

@tmontgomery Any thoughts on this?

**Comment by benjchristensen** [comment]
Re-reading the spec about CONNECTION_ERROR_NO_RETRY, it is somewhat confusing. 

Is it don't retry resuming? Or is it don't retry connecting to this server?

I think we should change as per @NiteshKant's suggestion.

**Comment by benjchristensen** [comment]
Proposed changed: https://github.com/ReactiveSocket/reactivesocket/pull/152

**Comment by benjchristensen** [comment]
change merged.
