### ISSUE TITLE
RESUME Identification Token and the R flag bit

### ISSUE THREAD

**Issue by vjn** [ReactiveSocket/reactivesocket#149]
It would be better to treat this similarly to how we do the metadata: if M is 0, then the metadata, including its size prefix are absent. Currently, even if R is 0, the resume identification token need not be absent: we're mandating that its size prefix is still present, and is zero.

**Comment by vjn** [comment]
Additionally, it would be better for the resume identification token bytes to follow the metadata, since the R flag bit is "after" the M flag bit.

**Comment by benjchristensen** [comment]
I have proposed a change based on this issue: https://github.com/ReactiveSocket/reactivesocket/pull/151

**Comment by benjchristensen** [comment]
Change merged.
