### ISSUE TITLE
REQUEST_CHANNEL and Requester/Responder Symmetry

### ISSUE THREAD

**Issue by vjn** [ReactiveSocket/reactivesocket#150]
Post creation of the bidirectional streams, REQUEST_CHANNEL should be (based on the semantics as discussed in the motivations document) symmetric. However, it is not. As currently specified:

- The requester sends a sequence of REQUEST_CHANNEL (and optionally REQUEST_N) frames.
- The responder sends a sequence of RESPONSE (and REQUEST_N) frames.

Perhaps the requester should send exactly one REQUEST_CHANNEL, and then both sides issue a sequence of RESPONSE frames (and REQUEST_N)?

**Comment by NiteshKant** [comment]
Yeah this awkwardness I think is "legacy" (ironically; the protocol isn't that old 😉 ) as request-channel was added later and is the only interaction model where there are more than request frame.

I think having a RESPONSE frame is more awkward as this is really a request 😄 

Probably the frames will be clearer if we do not call them RESPONSE frames and just call them NEXT frames and hence can be used in request and response.

Furthermore, I think we can do away with more than one request frame definitions and just have one with different request type. Request-Channel already has a flag for switching of initial-request N field.

**Comment by benjchristensen** [comment]
This is a valid point, and it is somewhat confusing right now. I think it would be clearer if a single REQUEST_CHANNEL was sent, and then a sequence of RESPONSE frames in response to the REQUEST_N.

This way both directions would send RESPONSE frames the same way, and we wouldn't have a sequence of REQUEST_CHANNEL frames on a single streamId, which seems semantically wrong as only the first triggers a "request".

@tmontgomery what do you think about this?

@NiteshKant @stevegury @robertroeser Would you support changing so that `requestChannel` uses RESPONSE frame in both directions?

**Comment by benjchristensen** [comment]
> I think having a RESPONSE frame is more awkward as this is really a request 

It can be considered a response to a request-n :-)

> Probably the frames will be clearer if we do not call them RESPONSE frames and just call them NEXT 

How about a rename to PAYLOAD then?

**Comment by tmontgomery** [comment]
PAYLOAD would be a good rename, I think. RESPONSE in the case of REQUEST_CHANNEL is quite awkward.

**Comment by benjchristensen** [comment]
Proposed change here: https://github.com/ReactiveSocket/reactivesocket/pull/153

**Comment by benjchristensen** [comment]
Also related to this: Request Channel Payloads from Requester #154

**Comment by NiteshKant** [comment]
Any appetite for this?

>>> Furthermore, I think we can do away with more than one request frame definitions and just have one with different request type. Request-Channel already has a flag for switching of initial-request N field.

**Comment by benjchristensen** [comment]
> I think we can do away with more than one request frame definitions and just have one with different request type. 

I'm not a fan of this. The frames do a good job of explicitly communicating what request is being made. We only have 4 types. We would have a new request frame that then has those 4 types as type ints ... which is exactly what the frames are already doing for us.

**Comment by benjchristensen** [comment]
#153 and #154 have both been merged, and the other item is thumbs-upped on not being pursued. Closing.
