### ISSUE TITLE
Minor comments on protocol.md

### ISSUE THREAD

**Issue by wenbozhu** [ReactiveSocket/reactivesocket#155]
1. when HTTP/2 is mentioned. I think it's better to mention HTTP/*. At the semantic level, HTTP is just a byte-stream protocol (like TCP).

2. "no state preserved across transport protocol sessions by the protocol" ..  does this contradict with the resuming support?

**Comment by yschimke** [comment]
The first point gets into exactly what is meant by HTTP/2 support.  Is it a single http/2 (byte) stream carrying the same bytes as TCP?

Or when supported, and no intermediate proxies, ReactiveSocket frames encoded as HTTP/2 frames with additional extended frame types?

**Comment by wenbozhu** [comment]
@yschimke 

> The first point gets into exactly what is meant by HTTP/2 support. Is it a single http/2 (byte) stream carrying the same bytes as TCP?

Same for HTTP/1, QUIC, SPDY etc. i.e. why I suggest mentioning "HTTP/*" or simply "HTTP" 

> Or when supported, and no intermediate proxies, ReactiveSocket frames encoded as HTTP/2 frames with additional extended frame types?

Then /length-prefixed required/ column should be changed to "No".

**Comment by yschimke** [comment]
I don't think SPDY is relevant anymore.  And QUIC is mostly HTTP/2 frames over a new transport IIUC [1].  And HTTP/1.1 support depends very much on stream vs frames.

[1]: https://daniel.haxx.se/blog/2017/01/26/quic-is-h2-over-udp/

**Comment by benjchristensen** [comment]
> when HTTP/2 is mentioned. I think it's better to mention HTTP/*. At the semantic level, HTTP is just a byte-stream protocol (like TCP).

2 of the 3 reference of HTTP/2 in the spec is very specific to HTTP/2 implementation details about streams and streamIDs so don't apply to HTTP/1.1. We specifically are talking about HTTP/2, as any use of HTTP/1 is going to be a hack of combining HTTP/1 connections (one for downstream, one for upstream).

**Comment by benjchristensen** [comment]
> "no state preserved across transport protocol sessions by the protocol" .. does this contradict with the resuming support?

I believe this is stating that no state at the transport level is expected, which is not. Resumption at the RS level does not require the transport to have any state across connections. 

@tmontgomery Is that correct, or does this wording need to be changed? Perhaps clarification about how RS resumption relates to this statement?

**Comment by wenbozhu** [comment]
OK. Thanks for clarification.

**Comment by tmontgomery** [comment]
@benjchristensen correct. I think it is OK as is.
