### ISSUE TITLE
KEEPALIVE timing

### ISSUE THREAD

**Issue by abersnaze** [ReactiveSocket/reactivesocket#16]
How long should server wait between KEEPALIVEs initiated by the client before it assumes that the client is dead?
How long should the client wait for the server to echo KEEPALIVE back before it assumes the server is dead?

**Comment by NiteshKant** [comment]
The spec mentions that a reasonable time period is 500 ms

>>> A reasonable time period between KEEPALIVE frames SHOULD be 500ms.

Although, I feel this should be overridable/agreeable during Setup.

[Handling the unexpected section](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#handling-the-unexpected) specifies that the determination of when to assert a peer is dead is an application choice. We may want to define best practices but not enforce it on the protocol end. Another best practice could be to tolerate X number of missed keep alive frames as a GC pause can make a peer delay a heartbeat and hence create a connection churn.

**Comment by abersnaze** [comment]
The client knows what the period is but is period communicated to the sever so it to can take action if the client misses X keep alive frames.

**Comment by NiteshKant** [comment]
Correct, that's why I said, it should be agreeable at the setup time.

**Comment by stevegury** [comment]
Agree with @NiteshKant here.

**Comment by tmontgomery** [comment]
Adding the keepalive interval and timeout to the SETUP would work. The server side would use those settings for that client.
