### ISSUE TITLE
Clarify Framing Layout

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#161]
I have received feedback from some that the layout of frames such as this are somewhat confusing:

```
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |                           Stream ID                           |
    +-----------+-+-+-+-+-+---------+-------------------------------+
    |Frame Type |0|R|M|L|S|  Flags  |
    +-----------+-+-+-+-+-+---------+-------------------------------+
    |         Major Version         |        Minor Version          |
    +-------------------------------+-------------------------------+
```

The part that is confusing is after FLAGS. To the right, with no vertical bar, that means we are skipping to the next line. It does NOT mean we are padding with 0s. 

Is there a better way of us communicating that?

**Comment by tmontgomery** [comment]
I am not sure how best to make this clearer. This is how HTTP/2 framing also lays out the fact that things are not aligned as well.

**Comment by benjchristensen** [comment]
@fiorix any suggestions on how to make this clearer?

**Comment by fiorix** [comment]
I'm fine with it now, but suspect that others might have the same question. We can probably close this and if it comes up again we can put more thought on it.

**Comment by tmontgomery** [comment]
Also, QUIC layout is using this technique also... not saying it is great or even OK. Just noting the usage.
