### ISSUE TITLE
Unreliable protocol

### ISSUE THREAD

**Issue by sgudiboina** [ReactiveSocket/reactivesocket#17]
The protocol documentation suggests that the protocol is unreliable. Please state it explicitly. If it is a reliable protocol, state how.

**Comment by ReactiveSocketAdmin** [comment]
What suggests it is unreliable?

**Comment by stevegury** [comment]
Actually the documentation suggest that the underlying transport protocol is reliable and garantee ordering.
We'll clarify this assumption explicitely.
Thanks for the suggestion.
