### ISSUE TITLE
Fragmentation of metadata and data

### ISSUE THREAD

**Issue by fiorix** [ReactiveSocket/reactivesocket#170]
Was going through the previous tickets related to fragmentation (https://github.com/ReactiveSocket/reactivesocket/issues?utf8=✓&q=is%3Aissue%20is%3Aclosed%20fragmentation) and noticed that most of them seem a bit outdated given that we currently have the F flag available on both requests and responses today.

I'd like to understand where we currently stand on this because during my work on the Go implementation I came across some scenarios that required assumptions about how metadata and data are fragmented.

For instance, the sender side of a Fire-N-Forget that has 1MB of metadata and 20MB of data would do the following (according to my assumptions):

Frame 1: header (F,M), metadata(1MB), data(~16MB)
Frame 2: header, data(~4MB)

Now if we consider a scenario where we had 20MB of metadata and 1MB of data, it'd look like this:

Frame 1: header (F,M), metadata(~16MB)
Frame 2: header (M), metadata(~4MB), data(1MB)

Is it correct to assume that in cases where either metadata or data should be fragmented the consumer side would always see metadata first? If this is true, then it makes it much easier for higher level APIs to implement proper streams as opposed to having to deal with fragmentation at the user level API.

**Comment by benjchristensen** [comment]
This would definitely be a good thing to clarify. I don't think the framing itself needs anything new, but a section describing the rules would eliminate different interpretations. 

@tmontgomery Do you have guidance on how this should best be done?

**Comment by tmontgomery** [comment]
Yes, this needs clarification. And an example sounds very good.

For clarity and ease, I think the way it should work is that the implementation should send metadata first. Any comments?

**Comment by fiorix** [comment]
I agree with metadata first. As far as the example goes, perhaps we could start with my example above unless someone else has a better idea. Would be a good addition to the [Fragmentation and Reassembly](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#fragmentation-and-reassembly) section.

**Comment by yschimke** [comment]
The difficulty as I see it for implementors is that naturally you end up with some Stream API for both producers and consumers if your payloads start getting into MB sizes.  Every Web framework does this for chunked encoding.

Nothing in the spec seems to disallow any of

- metadata first
- data first
- interleaved

At this point whoever writes the application code is in control of the ordering.  e.g. I might read both metadata and data from files off disk concurrently with different threads, this would effectively interleave the metadata and data.  

Are you going to change the spec to say that metadata always comes first and must complete before any data is sent?

If an implementation gets this API wrong, you end up with the issue that plagues using the java Process API, you must concurrently read both stderr and stdout to avoid blocking the producing process.

**Comment by fiorix** [comment]
That's a very good point about the Java Process API, and how things can get ugly especially with payloads of multiple MBs of metadata and data.

Despite that, I have no plans to change the spec until we're all on the same page with the idea that metadata must come first - which is nothing new given how frames are formatted anyway.

**Comment by yschimke** [comment]
To me this feels like an arbitrary decision.  Much like HTTP/1.1 headers come before the response. So we get to 

Allowed

- metadata and data provided in a single frame
- metadata completes before or in the first frame containing data

Not allowed

- metadata starts or continues past the first frame containing data.

It's interesting that HTTP/2 specifically broken from this model

https://svn.tools.ietf.org/svn/wg/httpbis/specs/rfc7230.html#chunked.trailer.part

> A trailer allows the sender to include additional fields at the end of a chunked message in order to supply metadata that might be dynamically generated while the message body is sent, such as a message integrity check, digital signature, or post-processing status. The trailer fields are identical to header fields, except they are sent in a chunked trailer instead of the message's header section.

**Comment by fiorix** [comment]
I think the tradeoff here is this: if we're willing to have high level APIs that handle fragmentation and  reassembly transparently we need clear rules for how to fragment and reassembly metadata and data. If don't have those rules we may have to always expose the bare bones API and let users implement fragmentation in any way they want - which can lead to very different implementations and decrease adoption since users would have to learn the wire protocol even for writing simple applications.

As far as comparing it with HTTP/2, we only have a generic "metadata" type that today cannot be differentiated between headers and trailers. Our current metadata (as per the frame format) looks more like headers than trailers IMO.

**Comment by tmontgomery** [comment]
The reason I mentioned metadata first is to be similar to HTTP. And also to make implementation simpler.

In general, I would rather have metadata and normal data proceed in any order. i.e. fragmentation can have both data and metadata proceeding as necessary. That is easy for the spec. But it is hard for implementations to handle. So, picking metadata first is simply for ease of implementation.

However, if I am mistaken or if we feel it is not a huge burden for implementations to allow both metadata and data in the same fragments, I am OK with that.

**Comment by yschimke** [comment]
For a protocol I'm very strongly in favour of allowing the data to proceed in any order.  So I'm actually against suggesting the implementations should just consume metadata first in case that is not the case.

I'd rather the 95% case be that you don't use fragmentation/streaming APIs.
The 5% can be complicated, but I'm also not clear on what that means for RxJava integrations etc.

**Comment by fiorix** [comment]
Assuming that 95% of the cases don't use fragmentation implies that users of any library understand the protocol's frame size limitations (of metadata and data) and also understand how fragmentation works, should they ever need it.

Allowing metadata and data to proceed in any order makes it much harder to provide higher level APIs, and can lead to the aforementioned problem of the Java Process API.

Both cases above could lower the adoption of the protocol by users that only care about shipping data upstream and downstream without knowing the nitty gritty of fragmentation and reassembly.

This is just my 2c, and I'm the new guy here, so please correct me if I'm wrong.

**Comment by yschimke** [comment]
I'd personally want to switch to some streaming mode before I hit the 16MB protocol frame size limits.  But I'd also want to be able to configure my server to reject clients trying to send me 16MB pills the swallow also :)

**Comment by tmontgomery** [comment]
@benjchristensen (and others) do we have a preference?

1. specify that data and metadata can be fragmented in any order as well as mixed. Easiest for spec and gives more freedom.

2. strict adherence to metadata (or data) fragmented first, then the other. Easier for implementations (maybe).

Honestly, I would prefer the former so that the spec is very lenient and I don't think that it is that onerous on implementations. But would like to know others opinions.

**Comment by benjchristensen** [comment]
When I implemented this for the Java version long ago (it never landed, but I implemented it!) ... I didn't treat either as special. I took a single Payload with data/metadata as the application wished to send, fragmented it over the wire, reassembled on the other end, and delivered a single combined frame with  the entire Payload. 

Why not just retain that simple approach so that it's purely a network level thing and doesn't change the API or behaviors?

In other words:

- sender writes Frame with Data/Metadata to ReactiveSocket
- ReactiveSocket fragments into multiple frames over the wire
- receiving ReactiveSocket reassembles into a single Frame
- receiver receives Frame with Data/Metadata

**Comment by yschimke** [comment]
I think that is punting the issue down the road, which I'm actually ok with if we are clear.  It works well for current use cases but doesn't clarify how to correctly and safely implement the protocol.  If we want to go down this route, we should just say in protocol version 1.0 that fragmentation is any order and is implementation and/or use case defined (prior arrangement).

Longer term:

My guess is the ample payload size (16MB) of the protocol means that the majority of users of the implementations won't even benefit from fragmentation, except for if you do it specifically to allow avoiding head of line blocking from a selfish producer.

It seems to me more likely that you would want to chunk the payloads well before the 16MB to enable certain use cases like 

- an efficient router of opaque RS frames, e.g. reverse proxy.
- immediate use of incoming streams, e.g. start writing to disk as stream comes in.
- stream producers e.g. stream of objects piped through streaming JSON library to an output stream.
- large response payload followed by a signature of the content.

If I needed to come up with a reactivesocket-api for now, I'd go for something like 

```
public interface StreamedPayload extends Payload {
  Optional<InputStream> getDataStream();
  Optional<InputStream> getMetadataStream();
}
```

**Comment by yschimke** [comment]
A counter argument to mine from the HTTP/2 world - https://github.com/quicwg/base-drafts/issues/76#issuecomment-281226785

**Comment by tmontgomery** [comment]
I think routing is a higher level concern than the protocol can effectively address. While metadata is a great spot to place routing information, it is by no means the only location. Nor the best location.

**Comment by tmontgomery** [comment]
In all honesty, I believe that metadata should be kept small. Something is very wrong if metadata needs to be fragmented, IMO.

Having said that, I do know that a user will want/need to have a lot of metadata for some reason (good or bad). Given that, fragmentation of metadata will need to be proscribed and allowed. Whether it is a good idea or not is immaterial.

One possible solution is to allow metadata and data to be fragmented however the application desires. I.e. payloads with fragments of metadata as well as data. And let higher level protocols determine if there is a strong priority to fragment metadata over data first or last in the stream.

This isn't really kicking the can down the road. This is placing a boundary between what is a concern for RS and what is a higher level concern.

**Comment by fiorix** [comment]
My concerns of not addressing this sooner rather than later are similar to what @yschimke describes wrt correctly and safely implementing the protocol.

When I read the spec and found that frames can have metadata, and the actual length of metadata is even longer than the frame length itself, I thought that metadata not only would be expected but also expected to be potentially large. The protocol allows metadata to be large. That's probably not common in most places but in many other places metadata will be large and fragmented.

The reason I opened this issue is because while implementing the spec I could not figure out the rules for fragmenting and reassembling metadata and data. We probably don't want to leave it open to interpretation.

As far as allowing metadata and data in any other, I have to disagree, because the worst case scenario *is* somewhere in the Java Process API land. Having fragments of the same stream with mixed metadata and data in no specific order will make streaming APIs more difficult and complex, probably requiring to either allocating memory to reassemble multiple frames, or spawning threads to stream the distinct metadata and data "concurrently". I can't see a cheap implementation coming out of this.

Anyway, I am fine with either approach so long it is clear in the spec.

**Comment by benjchristensen** [comment]
I don't understand what the correctness and safety issues are for this, so I must be missing something. 

### Application API

#### Sender

```cpp
BigData d; (25MB of data)
BigMetadata m; (20MB of metadata)
Payload p(d, m);
write(p);
```

#### Receiver

```cpp
void receive(Payload p) {
  BigData d = p.d;
  BigMetadata m = p.m;
}
```

### Frames (possible delivery with metadata first)

1) PAYLOAD frame

Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 16MB

16MB of METADATA
0MB of Data

2) PAYLOAD frame 

Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 4MB

4MB of METADATA
12MB of Data

3) PAYLOAD frame 

Frame length = 13MB
(M)etadata present = 0
(F)ollows = 0

0MB of METADATA
13MB of Data

### Frames (possible delivery with data first)

1) PAYLOAD frame

Frame length = 16MB
(M)etadata present = 0
(F)ollows = 1 (fragments coming)

0MB of METADATA
16MB of Data

2) PAYLOAD frame 

Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 7MB

7MB of METADATA
9MB of Data

3) PAYLOAD frame 

Frame length = 13MB
(M)etadata present = 1
(F)ollows = 0
Metadata Length = 13MB

13MB of METADATA
0MB of Data

### Frames (possible delivery with mixed)

1) PAYLOAD frame

Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 8MB

8MB of METADATA
8MB of Data

2) PAYLOAD frame 

Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 8MB

8MB of METADATA
8MB of Data

3) PAYLOAD frame 

Frame length = 13MB
(M)etadata present = 1
(F)ollows = 0
Metadata Length = 4MB

4MB of METADATA
9MB of Data

### Interpreting the frames

In all three of these scenarios, the sender and client do not need to pre-arrange which one they are doing, the frames communicate all the information needed. They communicate how many bytes are present for either metadata or data, and if fragments follow. The receiving implementation keeps receiving the bytes until no further fragments.

If an implementation wished to parse the bytes in a streaming fashion, instead of waiting for the entire payload, it is possible on all three of the above approaches to keep emitting bytes as they come in for either metadata or data across frames. 

What am I missing that would make this not just work?

**Comment by yschimke** [comment]
Your API is simple and unambiguous for the protocol.  

But inherently unsafe for the systems built using these APIs.  They need to buffer and collect each fragment of the payload until it is complete.  They are vulnerable to a DOS attack by sending 100MBs of data and then dribbling through small additional fragments. It is also very innefficient as I can't start consuming the first byte of the data until the last byte is complete.

As an implementor if I try to implement a streaming API on top of this I then I open up the issues that  we raised above.

We should be able to learn from every Web framework out there that streaming APIs are critical for anything that looks like chunked encoding.

**Comment by fiorix** [comment]
+1

**Comment by lexs** [comment]
I think we can defer a streaming RSocket API if the wire format still supports it, which it sounds like it does. Not enforcing ordering of Data/Metadata allows applications to send some metadata after they've written the (possibly large) data. @yschimke example here was a signature/hash of the data that could be computed on the fly.

That said, we should still work on clarifying the wording in the spec and add examples, I think @benjchristensen examples look pretty good.

**Comment by fiorix** [comment]
@lexs We don't have to discuss streaming APIs in depth here. Instead, we're trying to make sure they can be safely implemented based on what the spec describes, and today with unordered metadata and data (in fragmented streams) it does not make it easy for implementations to do so, at least on the consumer side.

**Comment by lexs** [comment]
It's not clear to me why interleaved data/metadata complicates any API, you still have to have either an API with one interleaved stream delivering Data/Metadata or two separate streams with complicated requirements.

Say we define metadata to come before data, how would the API look (in broad terms)?

**Comment by fiorix** [comment]
We can use the one posted by @yschimke as an example for a consumer API:

```
public interface StreamedPayload extends Payload {
  Optional<InputStream> getDataStream();
  Optional<InputStream> getMetadataStream();
}
```

With ordered metadata and data you can always consume/pipe one at a time. With mixed/interleaved you'd have to consume from both concurrently or reassemble their entire payloads before pumping bytes out to the streamer.

**Comment by benjchristensen** [comment]
> They are vulnerable to a DOS attack by sending 100MBs of data and then dribbling through small additional fragments.

How does adding rules to the spec prevent someone from doing a DOS attack?

**Comment by benjchristensen** [comment]
So if I understand correctly, @fiorix and @yschimke, you'd prefer just having a rule that says "When a Payload is fragmented, Metadata MUST be completely transmitted before Data"?

In other words, only allow the first option of my examples above?

1) PAYLOAD frame

Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 16MB

16MB of METADATA
0MB of Data

2) PAYLOAD frame

Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 4MB

4MB of METADATA
12MB of Data

3) PAYLOAD frame

Frame length = 13MB
(M)etadata present = 0
(F)ollows = 0

0MB of METADATA
13MB of Data

**Comment by fiorix** [comment]
I do prefer that for the long term, aiming at safe implementations that easily allow for streaming APIs. But I can live with the current mix so long it is clear in the spec.

What I still don't understand is what's the use case for having mixed metadata and data in fragmented streams.

**Comment by lexs** [comment]
> What I still don't understand is what's the use case for having mixed metadata and data in fragmented streams.

@fiorix: @yschimke mentioned http2 header/trailers. Say some headers can be delivered before you've sent the data but some can only efficiently be delivered after the whole payload has been written, like a checksum.

Regarding using InputStreams I'm not sure that's the correct abstraction here given that else is very pushy I think the API should be pushy too. I see us delivering two `Flowable`s, one for metadata and one for data.

**Comment by benjchristensen** [comment]
> What I still don't understand is what's the use case for having mixed metadata and data in fragmented streams.

Fragmented streams is the exception to the point of this protocol. The point of this protocol is streams, the requestStream and requestChannel interactions. Having requestResponse and fireAndForget are just side-effects, performance optimizations of "stream of one" or "stream of none" when I already have a connection established and don't need streams for some use cases. 

Having metadata associated with each payload is useful on streams.

**Comment by benjchristensen** [comment]
Example of metadata to deliver with message payloads:

- infrastructure metadata about network routes, latency, health associated with a particular message
- compression dictionary updates in the middle of a stream
- dictionary updates required for a particular message

**Comment by fiorix** [comment]
So yeah, the point for this whole issue is only about fragmentation and rules. I get that if you're using streams and channels it's quite common to have interleaved frames with metadata and data (or even only one or the other) but those are single units that are part of a stream or channel.

When it comes to fragmented messages the rules should be slightly different IMO, to effectively allow cheap reassembly on the consumer side.

**Comment by fiorix** [comment]
@lexs http2 trailers (which are just special headers) can only be sent after data, not interleaved.

**Comment by benjchristensen** [comment]
So is the proposed rule in https://github.com/ReactiveSocket/reactivesocket/issues/170#issuecomment-281731534 sufficient?

**Comment by fiorix** [comment]
Not quite, @benjchristensen.

What I expected in the beginning is this: whenever frames with the same Stream ID *and* the M,F flags set, metadata must be fully transmitted first, no matter the size of it.

This is not to be confused with the Stream and Channel flow control of RequestN and their continuation by another RequestN, or termination by a PAYLOAD with COMPLETE.

If we take the request/response flow, for example:

```
1. RQ -> RS: REQUEST_RESPONSE
2. RS -> RQ: PAYLOAD with COMPLETE
```

If the request must be fragmented because either data or metadata won't fit in 1 frame, it must always transmit all the metadata first, then the data. It's possible that at least 1 frame in the sequence with the same Stream ID will contain both metadata and data.

Now in a channel or stream, this also apply, but only as a fragmentation rule:

```
1. RQ -> RS: REQUEST_STREAM (REQUEST_N=3)
2. RS -> RQ: PAYLOAD
3. RS -> RQ: PAYLOAD
4. RS -> RQ: PAYLOAD
5. RS needs to wait for a new REQUEST_N at that point
6. RQ -> RS: REQUEST_N (N=3)
7. RS -> RQ: PAYLOAD
8. RS -> RQ: PAYLOAD with COMPLETE
```

Let's say that PAYLOAD 2 must be fragmented, which is, containing the F flag. First, I would assume that multiple fragmented frames count as 1 delivery (from the RequestN). If a single frame must be fragmented, then its metadata must be transmitted first.

This still allows for the same stream in the example above to have frame 3 with only data and frame 4 with only metadata.

Does this make more sense?

**Comment by lexs** [comment]
@fiorix It was just an example of something we couldn't easily support if we send metadata first.

**Comment by benjchristensen** [comment]
> What I expected in the beginning is this: whenever frames with the same Stream ID and the M,F flags set, metadata must be fully transmitted first, no matter the size of it.

I think that describes the example I provided, so I must not be communicating clearly enough :-)

I'll attempt a pull request to the protocol spec to clarify this and we can iterate on exact wording there.

**Comment by tmontgomery** [comment]
I think there are multiple things being collapsed here that I think might be good to tease apart.

1. A Streaming API is possible without having metadata delivered first. This is orthogonal to the order of M,F frames being sent. Data and Metadata can be individual streams as has been pointed out.
1. Opening implementations up to attacks is still just as possible with metadata first. Someone sends 100GB of metadata will block non-streaming APIs until it is delivered and complete and consume memory. While having no order preference allows a duplicate attack vector, it doesn't change the attack surface. It just means that data AND/OR metadata can be used.

My preference is to make metadata practices "better" and to think of using little metadata. So, I am quite fine with it being prioritized in the implementation. But I don't think we should choose that because we think we are gaining anything from streaming APIs and/or reducing the attack surface, because I don't think we are.

**Comment by yschimke** [comment]
> Opening implementations up to attacks is still just as possible with metadata first

I raised this in the context of an API that only delivers a complete Buffer (~byte[]) to clients. You have to buffer the data in memory within the implementation code even if its a slow client sending large payloads. An API that supports streaming can error the stream once it gets to X MB of unconsumed data.

**Comment by tmontgomery** [comment]
Yes, but that is an API choice and not the protocol. I totally agree on the API (nee implementation) being the vulnerability here. Not the protocol.

My concern is that we make a choice based on the correct impact. i.e. not picking to prioritize metadata over data because of a perception that it will lead to fewer attack vectors.

**Comment by fiorix** [comment]
I honestly think this is a flaw in the protocol though, because of the inconsistency between the format of a single frame and a frame that needs to be split in multiple fragments to accommodate its larger payload.

IMO multiple fragments should have the same layout of a single frame, but split in fragments looking like one giant frame, so it can be easily streamed and reassembled just like a single frame would.

Having fragmented frames with interleaved metadata and data will force implementations to either reassembly them concurrently in memory, or stream them concurrently to distinct consumer processes.

Despite all this, like I said before, I'm happy to move on and leave v1 the way it is. I can close this issue in a couple of days if everyone agrees with moving on.

**Comment by benjchristensen** [comment]
Proposed a change here: https://github.com/ReactiveSocket/reactivesocket/pull/194

**Comment by fiorix** [comment]
💯
