### ISSUE TITLE
Request-Response cancellation

### ISSUE THREAD

**Issue by fiorix** [ReactiveSocket/reactivesocket#179]
The possible sequences defined in https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#request-response states that cancellation happens from the requester to the responder, but I don't see how this would happen unless we're allowed to send cancellation frames within fragments of the request frame. Perhaps it is the other way around?

This:

```
RQ -> RS: REQUEST_RESPONSE
RQ -> RS: CANCEL
```

Should perhaps be:

```
RQ -> RS: REQUEST_RESPONSE
RS -> RQ: CANCEL
```

**Comment by fiorix** [comment]
I think I got it wrong. This is to send an arbitrary cancel frame after the entire request is sent, and avoid the peer to generate a response or to stop streaming a response.

**Comment by benjchristensen** [comment]
> This is to send an arbitrary cancel frame after the entire request is sent, and avoid the peer to generate a response or to stop streaming a response.

Correct.
