### ISSUE TITLE
Cancellation of fragmented streams

### ISSUE THREAD

**Issue by fiorix** [ReactiveSocket/reactivesocket#180]
Was going through a couple of use cases that brought the question of whether we should be able to cancel long fragmented streams.

The first use case that came up was this one: an HTTP server that has a /log endpoint that takes POSTs and forwards HTTP headers (as metadata) and HTTP body (as data) over to an rsocket connection via best effort fire-n-forget.

In this case, if the HTTP client is POSTing a long body in chunked transfer mode, and drops out before finishing, there is no way I can tell the peer rsocket that the current fire-n-forget stream should be cancelled; unless we're allowed to send CANCEL frames within fragments of the same stream.

Playing with my Go implementation, I created an HTTP to rsocket proxy that looks like this (error checking omitted for brevity):

```
        rscli, _ := rs.Dial("tcp", "localhost:9999",
                rs.HonorLeases(true),
                rs.Keepalive(time.Second, 2*time.Second),
                rs.MetadataEncoding("application/json"),
                rs.DataEncoding("application/json"),
        )
        defer rscli.Close()
        http.HandleFunc("/log", func(w http.ResponseWriter, r *http.Request) {
                rsw := rscli.Publish()
                defer rsw.Close()
                // send metadata
                json.NewEncoder(rsw.Metadata()).Encode(r.Header)
                rsw.Metadata().Close()
                // send data
                n, _ := io.Copy(rsw.Data(), r.Body)
                rsw.Data().Close()
                fmt.Fprintf(w, "%d bytes published\n", n)
        })
        http.ListenAndServe(":8080", nil)
```

This also relates to my other questions regarding fragmentation in #170.

If the HTTP client drops out mid-stream, the `io.Copy(rsw.Data(), r.Body)` that is streaming the HTTP body over to the rsocket stream will fail. In this case my underlying API can decide whether 1) it hasn't sent any frames out yet because it hasn't reached max frame length, then it should just bail; or 2) if it has already sent one or more frames with the F flag (and the peer is expecting more), send a CANCEL frame with the same Stream ID to tell the peer to discard the previous frames.

The second use case is an rsocket echo server using request-respond, that looks like this:

```
        leaser := func(local, remote net.Addr) rs.Lease {
                return rs.NewLease(10, time.Second)
        }
        handler := rs.HandlerFunc(func(conn rs.Conn) error {
                conn.HandleRequest(func(resp rs.WriteCloser, req rs.Reader) {
                        io.Copy(resp.Metadata(), req.Metadata())
                        resp.Metadata().Close()
                        io.Copy(resp.Data(), req.Data())
                        resp.Data().Close()
                })
                return nil
        })
        srv := &rs.Server{
                ReadTimeout:  120 * time.Second,
                WriteTimeout: 120 * time.Second,
                OfferLeases:  leaser,
                Handler:      handler,
        }
        srv.ListenAndServe(":9999")
```

And the client that connects to it is an HTTP to rsocket proxy again, that uses Go's standard context objects to handle cancellation:

```
        http.HandleFunc("/echo", func(w http.ResponseWriter, r *http.Request) {
                ctx := context.Background()
                ctx, _ = context.WithDeadline(ctx, time.Now().Add(5*time.Second))
                req, resp := rscli.Request(ctx)
                defer req.Close()
                // send metadata
                json.NewEncoder(req.Metadata()).Encode(r.Header)
                req.Metadata().Close()
                // send data
                io.Copy(req.Data(), r.Body)
                req.Data().Close()
                // read response metadata
                var hdr http.Header
                json.NewDecoder(resp.Metadata()).Decode(&hdr)
                // read response data and write back to the HTTP client
                io.Copy(w, resp.Data())
        })
```

Notice that I can set a deadline to the entire request and response cycle, which means the deadline may happen while we're still proxying the HTTP  body over to the rsocket peer. In that case I'd like my underlying API to either drop its work in case no frame has been sent out or send a CANCEL frame to tell the peer to discard any previous fragments received.

From my current understanding of the spec, today we only allow sending CANCEL frames after the entire request is sent, and this would tell the peer to not send a response (in case no frames has been sent yet) or to immediately stop sending more frames of a fragmented stream.

**Comment by fiorix** [comment]
Maybe @jakewins is also interested in this stuff.

**Comment by benjchristensen** [comment]
Cc @tmontgomery

**Comment by tmontgomery** [comment]
A responder that receives a CANCEL should immediately stop sending more frames of a fragmented stream. However, a requester must assume fragments will come in after a CANCEL has been sent due to the async nature of all transports.

Also, a CANCEL can be sent for channel at any time while requester is requesting. Even inter-fragmented frames.

**Comment by fiorix** [comment]
What about a responder that is still reassembling frames from multiple fragments with the F flag set and receives a CANCEL frame to stop doing its work? Is this allowed today, for example for fire-n-forget and request-response?

**Comment by tmontgomery** [comment]
@fiorix A reassembler that receives a CANCEL or ERROR while it has pending fragments, must always handle them by aborting the current frame and cancelling/erroring the current stream. So, yes, it is allowed to happen today and must cancel/error the stream as appropriate.

**Comment by jakewins** [comment]
@fiorix it looks like the direct issue is resolved by @tmontgomery above - but I'd love to chat about your Go stuff; did you end up writing one from scratch or forking off of mine? We should talk about joining forces :) You can reach me at jakewins at gmail.

Also - while I'm writing things, super stoked to see what y'all did with `0.2`, the explicit `PAYLOAD` and similar improvements to make flow control uniform between stream types helps, I think, reduce these kinds of ambiguities overall, awesome job.

**Comment by fiorix** [comment]
Clear, thanks @tmontgomery.

Hey @jakewins will reach out to you to discuss the Go stuff 👍
