### ISSUE TITLE
Interface description language (IDL) for ReactiveSocket

### ISSUE THREAD

**Issue by fiorix** [ReactiveSocket/reactivesocket#182]
Has there been any discussions about an IDL for ReactiveSockets yet?

Once the protocol spec is frozen I'd be down for hacking something up. Been looking at both [thrift](https://thrift.apache.org/docs/idl) and [grpc](http://www.grpc.io/docs/guides/concepts.html) IDLs to refresh my memory, and compare their IDLs and features available to each.

**Comment by benjchristensen** [comment]
There have definitely been internal discussions at both Netflix and Facebook. @robertroeser and @rdegnan I think have explored this space. And Thrift-based ones at Facebook. 

It's not a goal of ReactiveSocket to standardize this behavior though, so I would expect that to be a layer on top.

**Comment by fiorix** [comment]
Cool, thanks for clarifying.

At some point I might still try it though, and I'm sure others will do too.
