### ISSUE TITLE
Spec Organization

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#183]
Looking over the entire spec, are there improvements we can make to the structure for readability?

Here is the current outline (hyperlinks won't work):

----------
- [Terminology](#terminology)
- [Versioning Scheme](#versioning-scheme) 
- [Data and Metdata](#data-and-metadata) 
- [Framing](#framing)
  - [Transport Protocol](#framing-transport)
  - [Framing Protocol Usage](#framing-protocol-usage)
  - [Framing Format](#framing-format)
- [Operation](#operation)
  - [Frame Header Format](#operation-frame-header-format)
  - [Stream Identifiers](#operation-stream-identifiers)
  - [Frame Types](#operation-frame-types)
- [Connection Establishment](#connection-establishment)
- [Fragmentation and Reassembly](#fragmentation-and-reassembly)
- [Stream Sequences and Lifetimes](#stream-sequences)
  - [Request Response](#stream-sequences-request-response)
  - [Fire and Forget](#stream-sequences-fire-and-forget)
  - [Request Stream](#stream-sequences-request-stream)
  - [Request Channel](#stream-sequences-channel)
- [Flow Control](#flow-control)
  - [Reactive Stream Semantics](#flow-control-reactive-streams)
  - [Lease Semantics](#flow-control-lease)
  - [QoS and Prioritization](#flow-control-qos)
- [Handling the Unexpected](#handling-the-unexpected)
- [Resuming Operation](#resuming)

----------

- The RESUME and RESUME_OK frames are not under the "Frame Types" section, but under the "Resuming Operation" section. Should they be moved?  Should all of "Resuming Operation" just be a "Resuming" section underneath "Operation"?
- What does "Operation" specifically mean such that "Frame Types" is under it? Interpreting "Operation" to mean "how it operates" I would expect things like "Connection Establishment", but not the 3 things that are under "Operation" currently. In other words, what is different about "Framing" and "Operation" that puts "Frame Types" underneath "Operation"?

**Comment by tmontgomery** [comment]
"Resuming" is an optional part of the spec. To keep that distinct, it would be good to keep it a separate section.

"Operation" is probably poorly named. Those sections should probably be under "Framing".

**Comment by benjchristensen** [comment]
Makes sense, I'll re-organize the framing/operation piece a little.

**Comment by benjchristensen** [comment]
I simply removed the 'Operation' header and that made it flow far better. Left everything else as is for now.
