### ISSUE TITLE
Clarify COMPLETE for REQUEST_CHANNEL

### ISSUE THREAD

**Issue by lexs** [ReactiveSocket/reactivesocket#185]
It's not clear to me what setting the complete bit on the request frame means. Does it mean that the Requester won't send any PAYLOADS? Can we clarify that.

**Comment by benjchristensen** [comment]
Let me know if this clarifies it: https://github.com/ReactiveSocket/reactivesocket/pull/202

**Comment by lexs** [comment]
Yep!
