### ISSUE TITLE
Duplicated RESERVED Error Codes?

### ISSUE THREAD

**Issue by yunong** [ReactiveSocket/reactivesocket#19]
I noticed in the docs here https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#error-codes that error codes have ```RESERVED``` as ```0x0000``` AND ```0xFFFF```. Is this intentional?

**Comment by tmontgomery** [comment]
Yes, it is. Both all 0s and all 1s are good to reserve. Normally, I use all 1s for extension (such as with frame type EXT). Reserving all 0s is a convenient way to avoid having a blank field mean something meaningful.

This usually pertains to fields that act as decision points for processing.
