### ISSUE TITLE
Fragmentation and lease vs flow control

### ISSUE THREAD

**Issue by fiorix** [ReactiveSocket/reactivesocket#195]
Is it correct to assume the following:

1. Lease: from the lease perspective each frame counts towards the lease regardless of fragmentation

2. Flow control: multiple fragments of the same stream count as one RS towards N from the previous RequestN

**Comment by benjchristensen** [comment]
Lease only applies to incoming requests, so whether it is fragmented or not doesn't affect that. 

request(n) applies to PAYLOAD frames, multiple fragments of a single payload count as 1 credit.

**Comment by fiorix** [comment]
Thanks for clarifying. Maybe your last phase could be added to the fragmentation section of the spec for others to be clear on this as well.
