### ISSUE TITLE
Fragmentation of REQUEST_STREAM and REQUEST_CHANNEL frames

### ISSUE THREAD

**Issue by fiorix** [ReactiveSocket/reactivesocket#198]
In case the REQUEST_STREAM or REQUEST_CHANNEL frames must be fragmented (containing the **F** flag), should it contain the **Initial Request N** field in all fragments? Seems like a waste of resources to xmit/recv the same field over and over.

It'd make more sense to only send the **Initial Request N** field on the first frame, but this approach implies having a state machine to handle reassembly.

Thoughts?

**Comment by yschimke** [comment]
I've been assuming that only the first frame is of type REQUEST_STREAM or CHANNEL, and all additional request fragments are PAYLOAD frames.  why repeat the initial request header and allow for conflicting values?  I don't think the protocol is clear enough.  This part of the CHANNEL doc implies my thinking is correct, but its a weak assumption.

> A requester MUST send only one REQUEST_CHANNEL frame. Subsequent messages from requester to responder MUST be sent as PAYLOAD frames.

**Comment by fiorix** [comment]
Maybe we should clarify that this is also true for other request* frames that must be fragmented?

The frames that allow the F(ollow) flag today are:

* [REQUEST_RESPONSE (0x04)](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#request_response-frame-0x04)
* [REQUEST_FNF (0x05)](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#request_fnf-fire-n-forget-frame-0x05)
* [REQUEST_STREAM (0x06)](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#request_stream-frame-0x06)
* [REQUEST_CHANNEL (0x07)](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#request_channel-frame-0x07)
* [PAYLOAD (0x0A)](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#payload-frame-0x0a)

This allows the potential scenario of:

```
-- PAYLOAD frame 1
Frame type = One of the supported above: 0x04 - 0x07, 0x0A
Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 16MB

16MB of METADATA
0MB of Data

-- PAYLOAD frame 2
Frame type = PAYLOAD (0x0A)
Frame length = 16MB
(M)etadata present = 1
(F)ollows = 1 (fragments coming)
Metadata Length = 4MB

4MB of METADATA
12MB of Data

-- PAYLOAD frame 3
Frame type = PAYLOAD (0x0A)
Frame length = 13MB
(M)etadata present = 0
(F)ollows = 0

0MB of METADATA
13MB of Data
```

Also perhaps add @tmontgomery's [comment](https://github.com/ReactiveSocket/reactivesocket/issues/180#issuecomment-281117394) on cancellation of fragmented streams? This means frames 2 or 3 above could be either PAYLOAD (0x0A),  CANCEL (0x09), or ERROR (0x0B).

**Comment by benjchristensen** [comment]
I generally like this, though it feels like an exception in this spec to use PAYLOAD for anything other than the stream messages. But, I do agree it's cleaner than re-sending all other aspects of the initial request frame.

**Comment by benjchristensen** [comment]
@tmontgomery and @lehecka, what do you think?

**Comment by benjchristensen** [comment]
Proposed changes in https://github.com/ReactiveSocket/reactivesocket/pull/216

**Comment by benjchristensen** [comment]
merged.
