### ISSUE TITLE
FLAG Values?

### ISSUE THREAD

**Issue by yunong** [ReactiveSocket/reactivesocket#20]
I'm working on the JS implementation of this protocol. In the docs, I do not see explicit values for `Flag`. Does this information exist somewhere?

**Comment by tmontgomery** [comment]
Flags not specified should be assumed to be set to 0 when sent and not checked when received. I'll add clarity in the doc under the frame header.

**Comment by yunong** [comment]
That's what I assumed. However, what about the values for the other flags such as `ignore` or `metadata`?

**Comment by yunong** [comment]
It would be nice to have a table for all of the possible `flag` values similar to errors and types.

**Comment by tmontgomery** [comment]
`Ignore` and `Metadata` depend on the frame type and should already be specified for each frame type. Additionally flags for each frame type are also already specified. If there are gaps, let me know.

**Comment by yunong** [comment]
It'd be good to specify upfront what all of the Flags might be. I perused the entire document and I think there are only 3. `IGNORE`, `METADATA`, and `LEASE` Is this correct?

**Comment by yunong** [comment]
The reason I ask is I see in the Java implementation, there are `FLAGS_RESPONSE_C` and `FLAGS_RESPONSE_F` values that are not specified in the protocol doc. https://github.com/ReactiveSocket/reactivesocket-java/blob/master/src/main/java/io/reactivesocket/FrameFlyweight.java#L51-L54

**Comment by stevegury** [comment]
There's now 4 flags: `IGNORE`, `METADATA`, `LEASE` and `STRICT`.
`IGNORE`, `METADATA` are used in every frame
`LEASE` and `STRICT` can only be used with the `SETUP` frame.

Note: The java implementation is not complete yet.

**Comment by yunong** [comment]
@stevegury What about the `FOLLOWS` and `COMPLETE` flags here: https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#response-frame

**Comment by stevegury** [comment]
You're right, my bad. I only looked at the message a Requester is sending.

**Comment by yunong** [comment]
They also seem to collide with the `LEASE` frame, which is also `0b00100000`

**Comment by stevegury** [comment]
Oh I see, you want all the flags to be unique.
I don't think we need to ensure that (this is even too restrictive). The interpretation of a flag depends on the type of message you're reading.

**Comment by yunong** [comment]
That's cool with me.
