### ISSUE TITLE
METADATA and KEEPALIVE

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#201]
The KEEPALIVE frame doesn't support metadata, but LEASE, ERROR, and CANCEL do. 

Received feedback that it's either odd that KEEPALIVE is the only exception, or that LEASE, ERROR, and CANCEL do. 

REQUEST_N also does not have metadata.

So, why is KEEPALIVE different?

**Comment by benjchristensen** [comment]
CANCEL supports it so that there can be metadata about the cancellation. ERROR supports it for a similar reason. LEASE theoretically could use it, though I could see deciding to not have metadata for it.

**Comment by tmontgomery** [comment]
KEEPALIVE is a purely internal frame for protocol operation and doesn't need to support metadata (an application specific frame). Also, with METADATA_PUSH, the use of metadata in KEEPALIVE would be redundant.

**Comment by fiorix** [comment]
I wonder what a RQ or RS would do with the metadata of an ERROR or CANCEL frame, given that often times (always?) this is handled by the connection instead of an application.

**Comment by benjchristensen** [comment]
@fiorix Yes, most impls will not expose the frames, so I agree its usefulness is weak.

**Comment by benjchristensen** [comment]
Anyone think we should eliminate the METADATA from these various frames? Or just leave it?

Leaving it does open up ambiguity for implementations.

**Comment by benjchristensen** [comment]
Proposing deletion from ERROR, CANCEL, and LEASE here: https://github.com/ReactiveSocket/reactivesocket/pull/215

**Comment by benjchristensen** [comment]
@stevegury Please weigh in on this since you have the most involvement with LEASE semantics. Should the LEASE frame have metadata or not?

**Comment by stevegury** [comment]
The METADATA section in the LEASE frame is actually useful, it allows negotiating an improved flow control without upgrading the protocol. 

In practice, we've used it to add more optional fields (e.g. max rps) that the client is respecting if it supports it.

**Comment by benjchristensen** [comment]
Thanks for the input @stevegury. I've updated the PR to restore metadata on the LEASE frame. 

Do you have any reasons to keep metadata on ERROR and CANCEL?

I can't ever see how metadata on CANCEL would get delivered to the application. And ERROR already has the 'error data' section, and again, I can't see how to deliver it to the application gracefully when we optimize that to be UTF-8 text intended for the message in an Exception.

**Comment by stevegury** [comment]
I agree. METADATA on CANCEL may eventually be useful for debugging, but as it is very difficult to deliver the information to the application, I don't have any objections against removing it.

**Comment by benjchristensen** [comment]
Changes merged.
