### ISSUE TITLE
Strict Setup?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#209]
What does this mean on the SETUP frame?

> (S)trict: Adhere to strict interpretation of Data and Metadata.

**Comment by tmontgomery** [comment]
I believe (and maybe @stevegury , @robertroeser , or @NiteshKant ) can correct me that it was there to make sure that the mime types were followed. i.e. a server could not say yes unless it was an exact match.

**Comment by benjchristensen** [comment]
I'm struggling to see when this would ever be used. It's the client asking for a server to be "strict", but a server is going to do whatever it does, and if it fails to provide the client with data it can handle, the client won't use that server (and bugs will be filed, or customers lost).

Anyone have a reason to keep this? I'd rather not have things in the spec that are ambiguous.

**Comment by benjchristensen** [comment]
Proposing removal in https://github.com/ReactiveSocket/reactivesocket/pull/214 unless we have a concrete reason for this being used.

**Comment by tmontgomery** [comment]
I agree on removing it unless we have a strong reason. But would like to have the mentioned people weigh in.

**Comment by robertroeser** [comment]
We are using it from what I can tell - it should be ok to remove.

**Comment by benjchristensen** [comment]
@robertroeser Did Steve confirm as well from the Node.js side?

**Comment by benjchristensen** [comment]
Merged change and deleted it in https://github.com/ReactiveSocket/reactivesocket/pull/214
