### ISSUE TITLE
Resume Operation: Ignore bit in the RESUME frame

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#210]
What does this line mean:

> MUST send an ERROR frame if the server does not support resuming operation. This is accomplished by handling the Ignore bit in the RESUME frame. This is accomplished by handling the Ignore bit in the RESUME frame.

This is in the Resume Operation section.

Reason I ask is that the Ignore bit on the RESUME frame says it can't be ignored. And if it could be ignored we wouldn't be sending an error. 

I suggest deleting "This is accomplished by handling the Ignore bit in the RESUME frame.".

@tmontgomery Can you help me understand the intent of this?

**Comment by benjchristensen** [comment]
If it should be deleted, here is a PR: https://github.com/ReactiveSocket/reactivesocket/pull/217

**Comment by tmontgomery** [comment]
The intent was to point out that the Ignore bit on RESUME should always be 0. I.e. it can not be ignored. So, any compliant implementation seeing a RESUME should immediately error the connection as it does not understand the RESUME frame and it can not ignore it.

**Comment by benjchristensen** [comment]
Ah. That was not clear :-)

I think the wording is sufficiently clear in stating what must be done. And the frame clearly says it can't be ignored already.
