### ISSUE TITLE
Error Code CANCELLED

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#211]
When would the CANCELLED error code ever be used?

**Comment by tmontgomery** [comment]
I am unclear. I remember talking about it. But it may not apply with REJECTED.

**Comment by stevegury** [comment]
The idea of `CANCELLED` is to differentiate from `REJECTED` in the sense that it's not safe to retry.

E.g. in a situation like this: `A --> B --> C`
Server `B` cancelled the outstanding calls to `C` and reply to `A` with a `CANCELLED`; it's not safe for `A` to retry.

Even though it is not widely used, I would like to keep it.

**Comment by benjchristensen** [comment]
The description currently says this:

> The responder canceled the request but potentially have started processing it (almost identical to REJECTED but doesn't garantee that no side-effect have been started). Stream ID MUST be > 0. 

That does not refer to not being safe to retry, just that it may have side-effects. So by "not being safe to retry", does it just mean idempotence is not guaranteed?

**Comment by benjchristensen** [comment]
Changes proposed here: https://github.com/ReactiveSocket/reactivesocket/pull/219

I'd appreciate your review.

**Comment by stevegury** [comment]
Indeed, it doesn't mention "safe to retry", and it shouldn't, I was extrapolating the purpose of the message.
The "retriability" comes from the guarantee that no processing has been started on the server, and CANCEL explicitly doesn't give this guarantee (but REJECTED does).

**Comment by benjchristensen** [comment]
Thanks for the review. I felt similarly about not being explicit about retry.

**Comment by benjchristensen** [comment]
Change merged.
