### ISSUE TITLE
Error Code LEASE_ERROR

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#212]
The spec references a LEASE_ERROR error code, but we don't have that in the list of error codes. Should it have LEASE_ERROR? Or should the spec reference a different error?

> A Responder that receives a REQUEST that it can not honor due to LEASE restrictions MUST respond with an ERROR frame with error code of LEASE_ERROR. This includes an initial LEASE sent as part of Connection Establishment

**Comment by tmontgomery** [comment]
@stevegury do you remember this? Are you using it?

**Comment by stevegury** [comment]
IIRC, it was another error code indicating that the reason for the rejection was the exhaustion of the leases.
In the current Java implementation, we reply we a `REJECTED` error with the metadata containing `Lease exhausted.`.

It's not really important to have a particular error associated with the rejection, the only case that I can think of is for computing metrics.

So feel free to remove the reference to `LEASE_ERROR`.

**Comment by benjchristensen** [comment]
Does this work? https://github.com/ReactiveSocket/reactivesocket/pull/218/files

**Comment by benjchristensen** [comment]
Merged. Comment if change needed.

**Comment by stevegury** [comment]
👍
