### ISSUE TITLE
URI part of Metadata or Data?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#22]
Right now we have defined the default schema as having the URI in "Data": https://github.com/ReactiveSocket/reactivesocket/blob/master/Schema.md#data

The problem with this is that a routing layer (such as Zuul) must decode the Data payload, just to get the URI, even if it ignores the rest.

Should we instead put the URI in the metadata?

We would change the default schema to:

#### Data

- application/x.reactivesocket-data.v0+json (schema above encoded with JSON)
- application/x.reactivesocket-data.v0+cbor (schema above encoded with CBOR)

Fields:

```
Key: body [OPTIONAL]
Value: Object
```

#### Metadata

- application/x.reactivesocket-metadata.v0+json (schema above encoded with JSON)
- application/x.reactivesocket-metadata.v0+cbor (schema above encoded with CBOR)

Fields:

```
Key: uri [REQUIRED]
Value: String
```

--------------

However, this creates another problem. It couples the metadata and data together, which defeats the purpose of having different mime types for them?

Maybe we make "metadata" as the required fields, and leave "data" completely open? Like this:

#### Data

- no default schema, whatever the client/server chooses

#### Metadata

- application/x.reactivesocket.v0+json (schema above encoded with JSON)
- application/x.reactivesocket.v0+cbor (schema above encoded with CBOR)

Fields:

```
Key: uri [REQUIRED]
Value: String

Key: body [OPTIONAL]
Value: Object
```

**Comment by NiteshKant** [comment]
I believe URI should not be a part of the data and I think it makes sense to specify it in the metadata.

>>> Maybe we make "metadata" as the required fields, and leave "data" completely open?

+1 I don't think we should restrict what should be the format of data at all. It should be open and dependent on the application.

##### Should URI be required?

I don't think we should make it mandatory as it depends on what kind of routing/endpoint identification mechanism is used. eg: for an internal microservice call, we may not use a URI but a method id. In such a case, we will have to encode the method ID (an int/short may be) into a string and add an additional string length data.

**Comment by benjchristensen** [comment]
Regarding URI ... a URI could be just a methodId (i.e. /doStuff). There needs to be something known to look for though, whether it be called "uri" or "method" or "function", etc.

**Comment by NiteshKant** [comment]
Me and @benjchristensen synced up offline on this w.r.t URI. The point here is that it need not be a String, it can be a unique ID (int) for two endpoints that agree on an IDL. The name may be "endpoint".

**Comment by benjchristensen** [comment]
Done in Schema.md. It now only has `uri` in metadata.
