### ISSUE TITLE
More Prescriptive Interaction Metadata?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#23]
Want to explore whether we should be more prescriptive in what metadata is exchanged. An example of this is GRPC: https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md#requests It is very explicit in what metadata is exchange to force client/server to agree upon metadata allowing certain behavior, such as timeouts. It also defines more explicit error codes.

Is there a reason for us to embrace any of these ideas?

**Comment by benjchristensen** [comment]
Disclaimer: @niteshkant and I explored the use of GRPC but found it too limiting, since it only supports HTTP/2 as the transport, and only request/response. Otherwise there are definitely good things about it. Thus I want to ensure we use it as further inspiration.

**Comment by stevegury** [comment]
I wouldn't be too prescriptive here, and let some flexibility to the application layer on top of reactivesocket.

If you want to ensure that client and server can agree on specific METADATA, you can rely on the SETUP message with the `strict` bit to be sure that client and server can understand each others.

**Comment by NiteshKant** [comment]
@stevegury I think standardization is one aspect that will be an advantage if we prescribe, so every client-server do not have to get to an agreement (in or out of band) to agree on how do we send these settings. I do see value in standardizing timeout and some client identifier headers. #22 discusses standardization of "URI" (or a better name) to identify a unique method (":path" in grpc) on the server.

**Comment by NiteshKant** [comment]
@benjchristensen did you also mean to standardize the format of the metadata exchange in this issue? Thinking more about it I think there is more value in standardizing it over keeping it open for negotiation. Intermediaries will benefit by standard format as the metadata will be used by these intermediaries to analyze and process these requests.

**Comment by benjchristensen** [comment]
We've decided not to get any more prescriptive than we are. Applications can use SETUP or MimeType to layer more prescriptive behavior.
