### ISSUE TITLE
Stream ID uniqueness

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#24]
The [spec specifies](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#generation) that the stream IDs must be unique for a connection and any of the peer (client and server from the point of view of connection establishment) can initiate a stream and hence provide the unique ID.

How would an implementation make sure that the ID is unique? Should we prescribe any setup exchange like ID offset for the peer?

**Comment by benjchristensen** [comment]
It does not need to be unique across peers, just locally. The client generates the IDs, so it can start at 1 and increment each time a new request is made.

**Comment by stevegury** [comment]
@benjchristensen is right.
The implementation that we discussed with @tmontgomery was pretty straightforward:
A long that you increment for every REQUEST + a Set of active stream ids (just in case the long overflows)

**Comment by NiteshKant** [comment]
IDs locally unique to a requester is fine if there are no frame types that can be sent either ways on streams. In context of this example:

```
Client                                                     |                              Server

Request ID 1                                              -->

                                                         <--                      Request ID 1

FrameX(ID 1)                                              -->

                                                         <--                      FrameX(ID 1)
```

We need to make sure that `FrameX` is never of the same type from `Client->Server` and `Server->Client`, otherwise there is ambiguity around which stream does it actually belong to (ID1 initiated from client or server). Metadata push frame was one such instance that violated this "soft requirement", issue #35 removed it and it is no longer an issue, but it can be if we introduce any such frame in the future.

I think in general it is useful to have stream IDs locally unique for a connection (and not an RQ). For once, I can see debugging being painful if they are not unique to a connection. 

Uniqueness can simply be achieved by mandating that a client (initiator of the connection) uses odd IDs and server even.

>>> a Set of active stream ids (just in case the long overflows)

I would actually say that we establish a new connection if we overflow the long value. The old connection can then be alive till the time all active streams on the connection are completed.

**Comment by tmontgomery** [comment]
:+1: on the even/odd separation. Nice and clean.

**Comment by benjchristensen** [comment]
We have agreed to use this approach and @tmontgomery will put it in the spec. It's already been changed in the reactivesocket-java impl.

**Comment by wmiaw** [comment]
Please provide this context in the protocol definition.
