### ISSUE TITLE
Metadata usage clarification

### ISSUE THREAD

**Issue by jameskojo** [ReactiveSocket/reactivesocket#26]
* The term "metadata" is used throughout the document, although it's not always clear that it's always talking about the same thing. Please add a precise definition in the "Terminology" and disambiguate as necessary.
* Is the protocol itself agnostic all forms of metadata, or is there a specification that metadata should conform to which effects the processing of the frames?
* From Stream metadata, the protocol specifies a mechanism for transmitting metadata, and guarantees ordering. Is the maintence and persistence of the Metadata purely an app-side consideration? In other words, i imagine that for a given Stream, an application writer would want to accumulate Metadata about the stream throughout the lifecycle in some sort of "Stream Context" like data structure. If I understand correctly, the underlying protocol simply guarantees that the context is delivered in order (perhaps using internal buffering) but the protocol does not specify what is done with the Metadata after it has been produced. If that is correct, what exactly the difference between metadata and a request/response stream payload?

**Comment by tmontgomery** [comment]
The difference between Data and Metadata is an application concern. The only difference is that the protocol is providing a means for the application to demark what is considered Data and what is considered Metedata.

**Comment by benjchristensen** [comment]
The spec was updated to clarify this so considering this answered. Respond back if more to discuss.
