### ISSUE TITLE
Scope of the specification?

### ISSUE THREAD

**Issue by jameskojo** [ReactiveSocket/reactivesocket#27]
The protocol as specified seems to be agnostic to the underlying processing model for the request/response in that you don't specify an API for producing/consuming the streams. Do you plan to specifying a higher level an Rx based DSL or API?

**Comment by tmontgomery** [comment]
This will be language specific, but, yes, the API for the application usage will be similar to what is being iterated on in https://github.com/ReactiveSocket/reactivesocket-java/blob/master/src/main/java/io/reactivesocket/ReactiveSocket.java

**Comment by benjchristensen** [comment]
> Do you plan to specifying a higher level an Rx based DSL or API?

Wasn't intending on it, but perhaps it would be useful to call out in the spec the expected pseudo-code of what a requestor (generally the client) would look like?

It's something like this (but ignoring potential METADATA frames for this):

```java
Single<Response<Metadata, Data>> requestResponse(Request<Metdata, Data>> request);

Publisher<Response<Metadata, Data>> requestStream(Request<Metdata, Data>> request);

Publisher<Response<Metadata, Data>> requestSubscription(Request<Metdata, Data>> request);

Publisher<Void> fireAndForget(Request<Metdata, Data>> request);
```

**Comment by benjchristensen** [comment]
@jameskojo Is there anything you think should be included in the protocol spec itself regarding this?

**Comment by jameskojo** [comment]
No, the intention is now clear. Thanks for the clarification.
