### ISSUE TITLE
Clarification for bi-directional streaming use case

### ISSUE THREAD

**Issue by jameskojo** [ReactiveSocket/reactivesocket#28]
Does the protocol support requests Request Streams which span multiple frames?

For example does the protocol support the following example use case:
RQ needs to request for bookmarks from a bookmark service (RS) for a given customerId and a list of 1000 titleids.
RQ sends an initial frame containing the customerId and the first 100 titleIds.
RS immediate starts streaming back the bookmarks for a subset of the initial request
RQ sends a frame containing 800 titleIds *while* the initial responses are sent from RS
RS continues to stream back bookmarks
RQ sends a final frame containing the final 100 titleIds
RS streams the remaining bookmarks and a completion notificaiton.

**Comment by tmontgomery** [comment]
Currently all request types are idempotent. I.e. they are not fragmented and are not, themselves, a stream.

The application can implement what you mention by the use of a REQUEST_STREAM in both directions instead of within a single stream.

**Comment by NiteshKant** [comment]
Is the intent of sending titleids in 3 batches is to control the flow of response frames or the Ids are available to RQ in such batches?

If it is for controlling the response frames (flow control), this can be achieved by sending all IDs at the request time and then do a REQUEST_N whenever RQ is ready to get more data. 

However, if the pure flow control solution is not suitable, then can these be different requests? I would guess so if there is no state associated with the stream.

**Comment by benjchristensen** [comment]
@jameskojo Thanks James for getting involved and providing feedback. Similar to @NiteshKant I'd like to better understand what you are trying to achieve, as it seems related to flow control. 

If it is not flow control, but the need for multiple requests to mutate what gets sent, then perhaps https://github.com/ReactiveSocket/reactivesocket/issues/30 is what you're looking for, or as @tmontgomery said, with a REQUEST_STREAM in both directions.

**Comment by jameskojo** [comment]
The use case that I'm thinking of isn't really about flow control. I'm thinking about incremental processing in the case when the output stream of a given interaction is used to generate the input for a subsequent interaction.
For instance, imagine 3 different services: Edge, Recommendations and Bookmarks.
1. Edge gets a request to render the home page for user1.
2. Edge sends a REQUEST_STREAM to Recommendations to get all of the titles that it should display on the home page. Recommendations starts to stream back titleIds that it thinks are appropriate.
3. Edge makes a subsequent request to Bookmarks to get the user's position for each of the titles.
If we had bi-directional streaming, then we wouldn't have to wait until step 2 is complete before step 3 can begin.

**Comment by NiteshKant** [comment]
@jameskojo this is actually a good example when request data is not available at the time of the request initiation. This was part of the reason I was discussing the need for REQUEST_CHANNEL (#30) with @benjchristensen. The current models do not allow for this. 

Another way of solving this without REQUEST_CHANNEL would be to make independent requests for bookmarks (batched as per convenience). This does not mean that we would be waiting for Step 2 to complete before starting Step 3 as the requests are multiplexed. However, in cases where there is associated state with a request that is costly to re-establish across requests, this approach can be prohibitive. I am not sure if that would be the case for bookmark requests in your case.

**Comment by jameskojo** [comment]
@benjchristensen and @NiteshKant : #30 addresses my use case as well as the my concerns.
Using a pair of uni-directional streams to accomplish bi-directional stream semantics requires more complex application side orchestration.
IMO, bi-directional streams are a common enough use-case that they should have first-class treatment in the protocol, so +1 for REQUEST_CHANNEL or something like it.

**Comment by benjchristensen** [comment]
Cool. Thanks for confirming. I definitely agree with should support bi-directional channel use cases.
