### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#29]
Should we retain the ReactiveSocket name or find another?

Want to give a chance for broader debate and better ideas before we have production releases and are stuck with it.

Reasoning behind ReactiveSocket is:

---------
This library is directly related to several projects where "Reactive" is an important part of their name and architectural pattern. Thus the choice was made to retain this relationship in the name. Specifically:

- Reactive Streams
- Reactive Streams IO - proposed network protocol conforming to the Reactive Streams semantics
Reactive Extensions with RxJava and RxJS in particular
- Reactive Manifesto - particularly the "Message Driven" aspect

ReactiveSocket implements, uses, or follows the principles in these projects and libraries, thus the name.

---------

Potential problems with the name are:

- use of "Reactive" which has become buzzwordy, and I could see people arguing that this is diluting the word
- use of "Socket" which people may subjectively argue against
- multiple syllables
- could be trendy and thus dismissed

Benefits of the name:

- aligns with the "reactive" principles and projects as shown above
- descriptive

Please weigh in with your thoughts and alternatives if you have them.

If we do change the name, I'd want:

- the Github repo
- Twitter handle
- .io domain name

**Comment by tmontgomery** [comment]
I am fine with ReactiveSocket. But I am also not wedded to it if a better alternative arises.

**Comment by benjchristensen** [comment]
No one has provided a strong reason to not use ReactiveSocket offline or here, so closing out. 

If anyone has a better alternative, comment here and we'll reopen to discuss. We would need to make that change in the next several weeks though if it were to happen.
