### ISSUE TITLE
Metadata per Message

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#3]
Each message (up and down) needs to support metadata. This is similar to service tokens, headers or cookies in other protocols such as HTTP. 

Example use cases are:

- credentials and security tokens
- context & session
- routing metadata, such as for conditionally routing messages within infrastructure 
   - debug, A/B testing, stickiness, etc
- triggering fault injection, trace logging, etc across an entire call graph

**Comment by NiteshKant** [comment]
I am not yet convinced that we need metadata for every frame. The examples here sounds to me like they are the cases for having a metadata "per request" as opposed to metadata "per frame", eg: routing will not be per frame and so would fault injection, trace logging.

The closest protocol to ours being HTTP/2 also has headers (equivalent to metadata) associated to a stream and not a frame.

**Comment by benjchristensen** [comment]
I think we've discussed this in person since ... is this still an open question?

The use cases above are not per request, they can be per frame. For example, a request/stream of 100 "Video Manifests", each one with credentials/encryption/etc associate with that particular video. 

What is your recommended solution if not per frame?

Keep in mind how the application API would look like to consume the stream of data and metadata: https://github.com/ReactiveSocket/reactivesocket-java/blob/ae25df17c4c37caca82e1502c9d82fc96173cc02/src/test/java/io/reactivesocket/ReactiveSocketTest.java#L151

**Comment by benjchristensen** [comment]
Discussed in person ... we decided that having a Frame support both is the most flexible for all use cases and lets the application choose how to use it.
