### ISSUE TITLE
REQUEST_CHANNEL Interaction Type

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#30]
Some use cases have come up that may warrant another interaction model. The current 4 models all support a single REQUEST frame only. Bi-directional communication is happening under the covers, and can be achieved by an application using the 4 different REQUEST types in both directions. However, this does mean certain use cases would require the application to associate unidirectional streams, which somewhat defeats the point of having interaction models on top of a multiplexed bi-directional transport.

The two use cases I've come across both have similar semantics as follows:

- client requests a stream of data that initially bursts the current view of the world
- deltas/diffs are emitted from server to client as changes occur
- client wants to update the subscription over time to add/remove criteria/topics/etc

The goal is to avoid re-fetching the initial burst of all data again each time the client changes the subscription. 

Using just request/stream would mean the client cancels and re-requests each time, and gets a new burst of data on each change.

Another option is to maintain multiple separate request/stream connections that are more granular. This can indeed work in some cases, but if there is overlap amongst the criteria, it will still require canceling and re-requesting in some cases that are not purely additive.

The most efficient would be a custom application protocol on top that uses REQUEST_RESPONSE to send criteria, then REQUEST_SUBSCRIPTION to receive the events. This however is building a non-trivial behavior again on top of ReactiveSocket. It's no different than using HTTP GET to mutate server-side state and HTTP SSE to receive the changing output. 

Thus, the proposal is to add a 5th interaction type, REQUEST_CHANNEL that allows multiple request frames and multiple response frames (potentially infinite or finite).

From an application perspective, it would look like a channel with the ability to write and read ReactiveSocket Frames.

```java
// server
handleRequestChannel(Publisher<Frame> requests) {
       // subscribe to stream of incoming requests ... write Frames to output
}
```

This is almost easy to add ... the one trick I can think of is thus far we have only had to have REQUEST_N semantics flowing from RESPONDER to REQUESTER, and Lease behavior going from RESPONDER to REQUESTER.

In this case, it would make more sense to have REQUEST_N semantics go both directions, since it is a ReactiveStream Publisher that would represent the input. The Lease would control if REQUEST_CHANNEL can occur, but once the channel is established, then REQUEST_N would be used in both directions.

**Comment by stevegury** [comment]
:+1:

**Comment by benjchristensen** [comment]
I have added an implementation of this to reactivesocket-java in https://github.com/ReactiveSocket/reactivesocket-java/pull/21

**Comment by tmontgomery** [comment]
Language has been added to the spec for REQUEST_CHANNEL.
