### ISSUE TITLE
Layering?

### ISSUE THREAD

**Issue by rhs** [ReactiveSocket/reactivesocket#31]
The motivation provides some useful context. One question that comes to mind here is around layering. It appears that the protocol is currently described as a single layer that includes flow control, envelope/metadata, and several alternative interaction models. This is in some ways similar to where AMQP started. We ultimately ended up dividing the protocol into multiple layers because certain elements (e.g. flow control, envelopes, addressing/routing) ended up being fundamental to all interaction patterns, whereas a given endpoint rarely needs to use/understand the full variety of interaction patterns that can benefit from those more fundamental layers. By dividing the protocol into these layers, we found it became both easier and more efficient to implement useful general purpose intermediaries (i.e. proxies and routers) as they only need to concern themselves with those lower layers.

This may not matter much if you intend to use this as purely a client/server protocol, however if you intend this to form the basis of larger application-level networks, this question may be more relevant. For example if an incoming request ultimately triggers a number of dependent interactions of different types, I imagine you probably want the ability to correlate the dependent interactions back to the trigger. This implies the ability to share and propagate context across different styles of interaction.

Similarly, flow control generally needs to propagate from end to end, e.g. if service A uses service B which uses service C, then B may well be in the position of proxying service C's capacity to service A.

**Comment by tmontgomery** [comment]
We have some obvious layering already in the design.

- The frame length is a layer that should only be used for TCP and is not dependent on any other piece of functionality.
- The encoding of data and metadata is layered and decoupled from protocol interpretation.

There are two forms of layering. Explicit protocol layering in that a combination of protocols can be composed together to provide functionality. And implementation layering where the functionality of some protocol features is separately implementable.

I don't think that ReactiveSocket is that complex (as a problem to solve) that a combination of simple protocols would be advisable. In general, I think that if you don't intend to use a layer by itself, then there is no reason to make it a layer. Framing, I would use by itself or with something else. Data/Metadata encoding may change and be flexible and thus must be layered and decoupled.

Flow control, I don't think I would use by itself. Let me explain.

I think that the best candidates for layers are always the things that have 0 dependencies to other candidates. Or dependencies that can be made explicit. In addition, and more importantly, is the candidate used by multiple pieces of functionality in that making it its own entity of use or not.

Unfortunately, the way that ReactiveStreams flow control functions, there is no obvious means to totally decouple  the flow control semantics from the request and response semantics. But that doesn't mean the protocol can't lower the dependency somewhat. One simplification might be to eliminate the initial request N from request stream and request subscription and simply send a request N right after the request itself.  This would allow an implementation to decouple flow control (of responses) from request.

But essentially, making flow control a protocol layer (in that it can function independently) is not necessary nor advisable, IMO. However, with the change above, an implementation could layer it on optionally.

Similar to flow control is the lease strategy, which is a flow control concern as well. Lease strategy is already decoupled. Somewhat in an explicit manner via the connection establishment. However, it can't be totally decoupled as it is of primary concern and must be in place.

**Comment by benjchristensen** [comment]
@rhs Any further feedback on the response from @tmontgomery and approach we've chosen?

**Comment by rhs** [comment]
My question is really related to #30 and #32. Based on the interaction types described already, plus what is mentioned in #30 it seems that there potentially quite a bit more interaction patterns than there are flow control mechanisms. To someone with an async messaging background this is likely going to beg the question of why you haven't taken the approach of starting with a base layer defined in terms of one way flow controlled message streams and then layering your interaction patterns on top.

What I gather from @tmontgomery's response is that part of the answer is that you believe the choice of flow control mechanism is fundamentally dependent on the interaction pattern. If this is indeed the case, then this begs the question of how do you compose interaction patterns with differing flow control semantics (see my comment on #32).

**Comment by tmontgomery** [comment]
I don't understand how async messaging plays a role here. As my background is also in that area, I'm not making the connection. If you mean building everything on a one-way message passing model, that is possible, naturally, but the main goal is to support the Reactive Streams models. Not a general purpose messaging model.

Actually, flow control is orthogonal to the choice of interaction pattern (at least so far). Flow control within a stream (in either direction with semantics from #30 taken into account) is all handled by a single mechanism (the Reactive Streams request N mechanic). Flow control of the number of outstanding streams is handled on a connection-wide basis by a separate mechanic.

Composition of the number of outstanding requests vs. the flow of an individual stream can (and should be) done separately with composition. And they actually are right now. The determination of how they are controlled is done quite differently. Simply using the same frame layout wouldn't quite work as they need to communicate different pieces of info. Using the same mechanism for the implementation simply also wouldn't work as well either. Sometimes a duck is a duck and a goose is a goose. And not a duck with an abnormally long neck. I would very much caution against conflating these concerns at this stage.

**Comment by NiteshKant** [comment]
>>> Sometimes a duck is a duck and a goose is a goose. And not a duck with an abnormally long neck.

:) :+1:

**Comment by benjchristensen** [comment]
After further discussion on this, we still see the two types of flow control as different and do not see a reason to attempt combination of them.
