### ISSUE TITLE
Modeling demand?

### ISSUE THREAD

**Issue by rhs** [ReactiveSocket/reactivesocket#33]
The lease mechanism in the protocol allows clients that are connected to multiple servers to make a smart choice about which server to send a request (i.e. client side load balancing). If you wish, you can provide an analogous capability for servers. When multiple clients connect to a single server (or the fan-in/merge case), a server is faced with a choice of how to allocate its available capacity between all of the connected clients. This can be a tough problem. Distributing capacity evenly may not always work well because 90% of your load may come from 10% of your clients. In other words not all of the clients may have the same level of demand for that capacity. If the protocol doesn't model/communicate that demand, then the server has less information about how best to distribute its available capacity.

By modeling demand in the system (demand roughly corresponds to request backlog or potential for request backlog) you can create a strongly symmetric situation where servers have the same ability that clients do to make smart choices. In this sort of system, requests flow "downstream" through your network towards areas of greater capacity, and capacity flows "upstream" through your network towards areas of greater demand.

It turns out this sort of thing is quite useful in a messaging protocols since at the layer where everything is a one way message flow "demand" can be easily mapped to the message backlog at a given sender, and this is information the receiver doesn't have unless the sender chooses to share.

**Comment by stevegury** [comment]
@rhs I'm glad that you mention that, because we had the same idea. We plan to implement this exact mechanism in the future.
We didn't mention the details in the protocol specification because it should only be an implementation details of how the server distributes its lease.

**Comment by rhs** [comment]
Part of the question I was trying to bring up is whether this might benefit from being a protocol level concern or not. If the protocol is silent on this front than the server implementation can only use heuristics to try to predict client demand. On the other hand, if the client is allowed to communicate it's expected demand to the server, then the server has more information about how best to distribute its leases.

Put another way, if I understand correctly, the server has the following information on which to base its lease distribution decisions:
  + historical requests between that specific client and server
  + current request backlog between that specific client and server

The client has the following additional information on which to predict its future demand:
  + historical requests between that specific client and all server instances associated with a service
  + current request backlog between that specific client and all server instances associated with a service
  + backlog of non issuable requests (requests that can't yet be made because insufficient leases have been granted)

So assuming my understanding is correct and the client does in fact have additional information not available to the server, the key question I'm trying to raise is whether any of this additional information would be helpful to the server in figuring out how to distribute its leases.

**Comment by NiteshKant** [comment]
>>> The lease mechanism in the protocol allows clients that are connected to multiple servers to make a smart choice about which server to send a request

Just to be clear on this front, the [protocol specifies](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#lease-frame) that the lease can be sent by client or server. So, it is supporting the case for both client-server to establish supply-demand in either directions.

If I understand correctly by your second comment, you are suggesting something like:

```
Client -> Server 
Can I send 10 requests in the next 1 second?
Server -> Client 
You can send 8 requests in the next 1 second.
```
_I am using Client/Server in the above example for simplicity but it is in general for a RQ/RS_

Does this represent your suggestion? If so, I agree that it will result in a better distribution of load.

**Comment by benjchristensen** [comment]
This is an interesting one ... driving internal discussions. We will update more on this after we have clearer thoughts on it.

**Comment by benjchristensen** [comment]
Some concerns of mine of a client being involved ...

- how does a client know how much it should request (particularly when clients are generally running in a mixed environment with other clients)?
- complexity of implementations for both client and server to determine and coordinate, versus just one side being intelligent

**Comment by rhs** [comment]
To answer the question from @NiteshKant, I can confirm the example interaction you are providing is the sort of thing I'm talking about, although it's not necessarily the only type of information that might be useful to help a server distribute leases.

Another possible example of this sort of thing is modeling the logical service from where requests originate. By communicating this to the server, it could track heuristics based on the originating service rather than on a per connection basis. It could also enforce policies or initial conditions based on originating service, e.g. "allocate 20% more capacity to requests from service-A."

Also, I do realize the terms "client" and "server" are somewhat ambiguous in my language and that requester/responder are not necessarily coupled to the TCP notion of client and server. I'm still coming up to speed on some of vocab so bear with me and I'll try to be more clear in the future. (As an aside, is there a formal glossary somewhere?)

@benjchristensen To comment on your first concern, the way this is used for async messaging workloads (which may well be different from your expected workloads), the client isn't trying to request an optimal amount. It's not even a request really since there is no obligation for the server to use the information or respond in any way. The client is simply offering additional information about how many leases it believes it could use in an ideal world. The server is free to ignore this if it wants to or use it to compute a more optimal answer than it could without this information.

As for your second concern, I think that depends to some extent on the expected topologies and workloads. If you have a lot of clients fanning into a single server and each individual client has (relatively) infrequent bursts of requests, you can easily construct scenarios where the server has no good way to distribute its leases without this sort of information from the clients.

**Comment by benjchristensen** [comment]
After discussion, we have chosen to take the route advocated for by @stevegury
