### ISSUE TITLE
ERROR Frame Data as String byte[] in UTF-8

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#36]
We need the ability to convert an ERROR to a message readable by humans ... such as an `Exception` in Java. Thus, the byte[] being sent in an ERROR frame needs to be String bytes so it can be turned back into a String. 

This means we must also define the encoding type: UTF-8

Why not support the MimeType encoding for ERROR?

a) because the error could have been caused by the encoder trying to encode into the MimeType
b) because the thing processing the error may have no knowledge of the MimeType or processor
c) because this would require a consistent MimeType to always deliver the error in the same way, which goes against the principle of allowing the MimeType to be defined by the application tier.

**Comment by tmontgomery** [comment]
Will update the spec to reflect this.
