### ISSUE TITLE
REQUEST_N Frame Metadata

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#37]
We should reconsider having metadata on the REQUEST_N frame. What will an application do with that? How would we expose it to an app?

**Comment by tmontgomery** [comment]
The protocol can specify it and allow it. But an implementation could not implement it.

But, yes, I would consider whether it actually makes sense or not. I don't think it does. REQUEST_N is a protocol concern and taking out unneeded things is probably a good thing.

**Comment by NiteshKant** [comment]
+1 I don't think we need metadata for REQUEST_N. Also, do we need it for CANCEL and ERROR? If we think that RS/RQ will send reason for error and cancel as metadata, we may want to standardize the metadata name as being discussed in #23

**Comment by tmontgomery** [comment]
Metadata has been removed from REQUEST_N.
