### ISSUE TITLE
Stream ID clarifications

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#4]
I have a few clarifications w.r.t the stream identifiers defined in the [protocol](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md).

>> Stream IDs are generated by a client.

Doesn't this impede server initiated requests usecase or am I missing something here?

>> Stream ID generation SHOULD start at 1 and increase contiguously for each request type used by the client.

Is this suggesting that I can not skip stream IDs i.e. I can not have a stream ID of 1 then 5 then 10, etc.? I think in general it is an ok restriction however, it would mean that there is a globally (for the connection) synchronized counter for stream IDs in the client code. If from the protocol point of view we are not inferring status of one stream by virtue of a start of another stream (like in HTTP/2) we can actually relax this requirement to __a stream ID must be locally unique for a connection__. If this is done, a client can actually shard ID spaces and eliminate the globally synchronized counter.

**Comment by tmontgomery** [comment]
I like the uniqueness clause. So, will add that so that we can eliminate the contention.

That should read "Stream IDs are generated by a Requester". A client may be both a Requester and a Responder.

**Comment by tmontgomery** [comment]
Take a look and see how it reads now.

**Comment by NiteshKant** [comment]
Sounds great now!
