### ISSUE TITLE
Enabling keep alive by default?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#41]
Today the protocol supports keep alive frames but does not provide any guidelines on whether it should be enabled by default or not. So, it is left up to the implementations or the eventual users to decide whether it should be enabled or not for a connection. 

There are a few cases, as explained below, when in absence of keep-alive, a request will be in a state of silent failure. All scenarios below are when the connection is in half open/closed state and hence data is exchanged in one direction but not the other.

* __RQ creates a new REQUEST_STREAM or REQUEST_SUBSCRIPTION request__: Since, the protocol does not require RS to acknowledge a request creation, if RS is unavailable, RQ will never know if the response is delayed or RS has not received it and hence it will never get any data as a response. Typically long live streams do not have timeouts as the times are unpredictable, so RQ may wait forever.

* __Existing `REQUEST_STREAM` or `REQUEST_SUBSCRIPTION` requests__ : If in the middle of these requests, the connection is half closed, then RQ will not be aware of this state change and potentially wait for the response forever.

* __Cancel of an existing request__:  RS may continue to process a request and keep sending data for requests even when RQ has cancelled the subscription. This may be quiet an overhead for long running stream subscriptions.

These edge cases (and possibly more) are subtle and are all solved by having keep-alive turned on the connection, however, we do not have keep-alive on by default. So, should we mandate that keep-alive is turned on by default and there is a setup that disables it, as opposed to explicit enabling by default?

**Comment by tmontgomery** [comment]
SETUP could use a value of 0 for Keepalive interval to signal that it won't send KEEPALIVEs. That could cause a server to send back a SETUP_ERROR if it must support it. Thus the server can reject.

**Comment by NiteshKant** [comment]
@tmontgomery I agree that it is possible for client-server to agree/disagree on keep-alive in the current state of the protocol. I am suggesting that we make keep-alive turned on by default in the spec so if the client/server do not disable it, it will be on. Disabling will be a conscious choice with the knowledge of the edge cases that may arise by turning it off. Currently, the spec seem to suggest that keep-alive is opt-in and not opt-out or at least such a suggestion is absent.

**Comment by tmontgomery** [comment]
Hmm. This might come down to wording. Do you have some wording in mind to clarify it?

**Comment by NiteshKant** [comment]
Let me send a PR for this.

**Comment by tmontgomery** [comment]
Updated KEEPALIVE wording. Take a look and see if this works.

**Comment by benjchristensen** [comment]
Updated the wording in the spec.
