### ISSUE TITLE
Frame header optional length is problematic

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#44]
The frame header states the frame length field is included depending on the underlying protocol. I don't think this is a good idea. It makes building and parsing the frame more difficult with lower-level dependencies that may or may not be something the protocol stack can know. It also means the receiver has to figure out if the frame length is there or not. And it means your protocol cannot be used across multiple underlying protocols (which is how the Internet actually works).

**Comment by tmontgomery** [comment]
The protocol is used over a transport protocol. This must be instantiated. That protocol provides framing or it doesn't. This is a static concern for this association. Thus it is truly trivial to know whether the frame length is needed or not. This includes whether it is used in a wireshark dissector or a protocol implementation.

**Comment by wmiaw** [comment]
MSL provides two potential sources of framing: entire MSL messages, and a single message's payload chunks. Considering MSL, the best thing to do is to use multiple payload chunks, and not multiple MSL messages. However the payload chunk boundaries are not provided to the receiving application. Reactive Socket will not work properly in that case.

Ethernet provides framing of its own, with frame sizes. However if Ethernet then connects to an ATM network, the frame sizes are going to change, while the data being carried on top (your Reactive Socket frame) will not. And you are making the receiver read exactly the amount of data in a single ATM frame (which it probably cannot do at the Reactive Socket stack layer) and assuming that is your frame size.

HTTP can provide a Content-Length header but that is optional. You may not know if the HTTP stack you are using will include that automatically, and you may not have the ability to inspect it directly to figure out what the size of your Reactive Socket frame in the HTTP body should be. If using Chunked transfer-coding to send multiple Reactive Socket frames within a single HTTP request, you probably cannot not get the individual chunk sizes from the HTTP stack.

**Comment by tmontgomery** [comment]
I would like to more clearly understand MSL requirements here. Maybe talking next Tue is an option?
Would want to know where MSL sits (on top of Ethernet/ATM, UDP, TCP, higher?), does it reassemble chunks before passing onto apps on top, etc. But better handled, I think, as a conversation in person. Maybe you, @benjchristensen , and I can meet.

But, let me add some clarity.

Ethernet is not a transport protocol. Also, it doesn't meet the definition in the Terminology section of the spec for "Transport Protocol" needed for ReactiveSocket.

For framing, the minimum viable functionality would be IP fragmentation (which is what you mention with Ethernet MTU vs. ATM "MTU" (ATM uses "cell", IIRC). IP fragmentation would limit the usable frame size for ReactiveSockets. It would reassemble before allowing protocol processing as it does UDP. Same with UDP datagrams as a viable alternative (if UDP had reliable delivery, that is).

For dissectors like wireshark, reassembly is done by the wireshark application/library. Plugins easily can (and do) leverage it for dissection that spans Ethernet/ATM frames. Having done (many times!) framing and reassembly on top of these protocols, it can be handled.

A mapping of ReactiveSocket unto HTTP (which is not defined) could define (and mandate use of) Content-Length as a means to do framing. WebSocket already has framing. Aeron already has framing. SCTP already has framing. HTTP/2 has framing. TCP does not have framing.

**Comment by wmiaw** [comment]
If you are willing to increase the requirements provided by the underlying protocol, or limit to a specific set, then that addresses the issue but presents integration problems and limitations.

For example, even if you mandated use of Content-Length and prohibited use of Chunked transfer-coding when using HTTP, no one would necessarily be able to guarantee those requirements are satisfied. Especially if an HTTP proxy is involved.

If it is decided that these problems and limitations are OK, then that's fine. But personally I would not like that.

**Comment by stevegury** [comment]
My view of this problem is simple:
1. In the case of underlying protocol supporting framing, I don't see why we should transmit another frame length (info is already present)
2. If the underlying protocol doesn't support framing, then you don't have the choice, you have to send it.

The first 4 bytes could be viewed as another transport that only does framing.

**Comment by NiteshKant** [comment]
@wmiaw I do not understand your concerns and the reference to HTTP/1 content-length and chunking is totally conflating the scenario. HTTP/1 does not provide framing and hence it will fall into the category of protocols that do not define framing semantics and hence all Reactive Socket frames on top of HTTP/1 would contain the length bits. The use of content-length and chunking does not alter this requirement.

Do you have concrete protocol examples on which Reactive Sockets protocol as defined today will not work?

**Comment by wmiaw** [comment]
Client to network proxy communication is HTTP/2 over TLS. Network proxy to data center communication is MSL over TCP. Network proxy is aware of HTTP/2 and MSL. It is not aware of Reactive Sockets. Client knows it is using HTTP/2 so it excludes the Reactive Sockets frame lengths. Data center receives Reactive Sockets without any way to figure out the original frame lengths.

**Comment by tmontgomery** [comment]
@wmiaw wouldn't that be: HTTP/2 over TLS = Reactive Socket no framing. MSL over TCP = Reactive Socket with framing (assuming MSL doesn't have framing just for simplicity). i.e. at each hop, the frame length would be added if needed or stripped if not? It is a transport handoff anyway.

**Comment by wmiaw** [comment]
@tmontgomery it was stated above that HTTP/2 has framing in the context of Reactive Socket, which I took to mean the sender would exclude the Reactive Socket frame lengths assuming the receiver would pull the frame lengths off the HTTP/2 layer. MSL doesn't provide its framing boundaries to the receiver, so the receiver has no length data anywhere now. (Even if MSL did, the network proxy may not match one HTTP/2 frame to one MSL frame.)

The Reactive Socket frame length could be added/removed by the network proxy, but only if the network proxy is aware of Reactive Socket and its entire Reactive Socket stack is compatible with the sender and receiver stacks. But in my concrete scenario the network proxy is not aware of Reactive Sockets. Maybe it is a network proxy run by the Chinese government or AOL.

**Comment by tmontgomery** [comment]
I was assuming the type of "network proxy" was a layer 7 gateway under application control. But it sounds like you mean an HTTP-style proxy. Correct?

As MSL doesn't expose framing, any usage of ReactiveSocket would need to use its own framing over it.

**Comment by wmiaw** [comment]
Yes, an HTTP-style proxy for example. Reactive Socket would need to use its own framing but the two Reactive Socket endpoints can't know their view of the world is different from each other until after they talk at least once.

**Comment by tmontgomery** [comment]
I'm thinking it makes more sense to always include framing as you suggest. The assumption so far has been a transport hop was also an application (as in ReactiveSocket handoff) hop. If that assumption is incorrect, then it is simpler to just always include the frame length.

**Comment by NiteshKant** [comment]
For the specified usecase, AFAIU, the SETUP will not succeed as MSL data received without any framing will result in a parsing error by the receiver. It is the same as sending garbage data on HTTP for example.
As per the protocol, MSL is not a valid transport for Reactive Socket as it does not provide framing. So a network proxy translating from HTTP/2 (framed) to MSL (unframed) is an illegal transformation and the receiver would be able to know that it is illegal data.
OTOH, let us consider another protocol like WebSocket which the network proxy transforms to, then the network proxy must mediate between the frame lengths for HTTP/2 and WebSockets. Since, Reactive Socket is the data part for these protocols, it does not change between the mediation. 

What am I missing here?

**Comment by stevegury** [comment]
I see your point now, my assumption is that any proxy would be at the application layer.

I would argue that the type of proxy you described is invalid because it doesn't provide the garantee required by reactivesocket.
In your example, after decoding the reactivesocket frame (over HTTP/2 with framing), the proxy should provide the length on the MSL side because it isn't a transport protocol supporting framing. If the proxy doesn't do that, it's invalid w.r.t. the reactivesocket specification.

**Comment by tmontgomery** [comment]
I think some context and math here can help determine whether frame length being optional is worth the cost.

Assumptions (please comment): 
- NIC bandwidth is the only limiting factor. And not network MTU.
- Frame Length being optional is an optimization for network efficiency.
- IPv4 over TCP assumed for operation at very minimum. For each frame, this is 20 bytes IP and 20 bytes TCP. i.e. 40 bytes overhead per frame. Minimum.
- IPv4 over UDP assumed for operation with Aeron. For each frame, this is 20 bytes IP and 8 bytes UDP. Aeron overhead is 24 bytes. Total overhead is 52 bytes per Aeron fragment.
- Fire-And-Forget (FnF) with 12-15-byte payload is worst case for efficiency.

Question: does frame length, when taken into account, significantly impact network utilization. In this context, network utilization is `data / (data + control)` and expressed as a ratio. A higher value means a more efficient protocol.

As of this writing, the overhead for a FnF message is 8 bytes without frame length and 12 bytes with frame length.

Taken with the values above.

- IP+TCP without frame length: 15 / (15 + 8 + 40) = 24%
- IP+TCP with frame length: 15 / (15 + 12 + 40) = 22%
- IP+UDP+Aeron without frame length: 15 / (15 + 8 + 52) = 20%
- IP+UDP+Aeron with frame length: 15 / (15 + 12 + 52) = 19%

What this boils down to then is a 1-2% savings (at most) on the NIC bandwidth.

For a 1Gbps NIC, the number of FnFs per second:
- IP+TCP without frame length: 2097152
- IP+TCP with frame length: 2003249
- IP+UDP+Aeron without frame length: 1789569
- IP+UDP+Aeron with frame length: 1698958

What this boils down to then is a difference in optimal FnFs per second of around 90K.

**Comment by tmontgomery** [comment]
I'd like to see a show of hands given the differences above whether having an optional frame length is _worth_ it or not.

I will abstain.

**Comment by benjchristensen** [comment]
I do not feel strongly either way. Though it seems wasteful to include it when it's not needed. And every little decision like this adds up, so I generally prefer not adding overhead if it is not needed. Thus, I lean towards leaving it conditional on the transport being used so it doesn't need to be sent. 

If there are objective use cases as to why this would cause problems, then I'm fine giving up the 1-2% throughput in the optimal FnF use case (which is modeled after expected Hystrix event stream usage). The discussion above leads me to believe that the proxy case is the only one that seems legit. But that still hasn't fully convinced me, because a proxy can't just dumbly pass a frame through, it has to comply with the ReactiveSocket and transport protocols on both sides.

**Comment by NiteshKant** [comment]
Similar to @benjchristensen I am inclined towards not including them with every frame when running over a protocol that provides framing as I don't see valid reasons for including.

**Comment by stevegury** [comment]
Agree, the gain itself is not the main reason of not including the length. It's just a redundant piece of information.
I tend toward not including the length when used on top of protocols that support framing.

**Comment by benjchristensen** [comment]
We have clarified the spec to specify when LENGTH is required, and when it is not required. It MUST exist on TCP, and MUST NOT exist on Aeron and WebSockets. No other transport protocols are officially supported at this time.
