### ISSUE TITLE
Service ID + request params undefined

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#49]
Request frames indicate the payload data should contain a service ID and request parameters. The encoding of these two things are undefined. I suspect in fact these two things are part of the application protocol running on top of Reactive Socket and they should not even be mentioned in the Reactive Socket protocol.

**Comment by tmontgomery** [comment]
Correct. Although, I think there is a default Schema.md file that talks about a minimal set of payload for requests.

**Comment by NiteshKant** [comment]
In issue #22 we decided that service ID and parameters would be part of the metadata, but looks like the spec did not get updated with that decision. The encoding of both data and metadata are specified in the setup frame via MIME types.

I think at this point Reactive Socket is more of an application protocol as it defines more of application semantics (requests, leases, etc.) than transport semantics, so personally I don't see a problem specifying these as they anyways be required by any serious application (running more than one endpoint on a server)

**Comment by wmiaw** [comment]
The specification should then provide enough information that an implementer can accept a service ID and parameters (in what form? a map of string -> string?) from a caller and know how to encode the metadata for specifically supported MIME types. As well as how that will work when needing a service ID and parameters to be mixed in with other random application metadata.

**Comment by benjchristensen** [comment]
The protocol does not address serviceID/parameters data. It is completely up to the application, and the application determines what the client/server agrees upon using the SETUP frame.
