### ISSUE TITLE
Connection establishment

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#5]
The current protocol spec suggests that an absence of a response from the server suggests accept of the setup. I think we can break it down as per use case:

- __Initiate with prior knowledge__: In this case, the client can start sending requests without waiting for the setup acknowledgment from the server. This would typically be done because the client knows meta information about the user, primarily I see it for internal communications (IPC in microservices) as I can get this data from a service registry.
- __Multiple options handshake__: In case the server + client supports multiple versions of the protocol, then the server can send the best matching protocol. In this case, the client would wait for the server response of accept.
- __Single option setup__: If the client supports only a single version of the protocol, then the client would wait for the acknowledgment from the server that the version is supported.

Broadly, making an acknowledgment from the server optional from the client. The current spec is limiting in this regards that it can not support handshake as opposed to making it optional.

**Comment by tmontgomery** [comment]
In general, the preference is to reduce round-trip delay by utilizing false start semantics. I.e. the client assumes SETUP will be accepted. Thus allowing either the client or server to send Requests immediately upon sending/receiving a SETUP. The burden is shifted to the Responder then to allow the connection to continue or not (and to fulfill a request or not).

@benjchristensen and I discussed, for simplicity, the general idea that the client will include in its SETUP that it supports a _single_ format, for example. The server will either accept this or not. This allows all the complexity of supporting versions and formats to be server side and keep clients nice and simple. It also means fallback or anything else will be handled at a multiple retry level.

I'm updating the doc for clarity, let me know what you think.

**Comment by benjchristensen** [comment]
I think that has been addressed, and the reactivesocket-java impl now supports the SETUP behavior. @NiteshKant let me know if there are further concerns.

**Comment by benjchristensen** [comment]
Discussed in-person. We're in agreement with how it is implemented and specced.
