### ISSUE TITLE
Error handling / recovery rules for corrupted / malformed frames is not defined

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#50]
How should the Reactive Socket stack handle receipt of corrupted frames? Either that results in parsing failures or messed up data lengths that cause incorrect parsing and the next byte no longer being the start of the next frame?

When this happens, what is told to the application? How should the next frame be properly identified to recover the communication channel?

The protocol definition only specifies the underlying protocol is reliable, which only refers to delivery and non-delivery of data. It does not specify that it also provides data integrity.

**Comment by stevegury** [comment]
You're right, we should explicitly recommend a behavior in the spec.
I believe we should close the connection, and we shouldn't try to recover from that.

**Comment by benjchristensen** [comment]
Yes, we are missing a connection level error. I discuss this in #59 where I reference the approach HTTP/2 takes with the GOAWAY frame. It is a best-effort termination of a connection. We could send it then shut down the connection. The receiver may or may not receive the GOAWAY frame depending on the nature of the failure, but it's better than just killing a connection without any signal.

I don't think we should call it GOAWAY though, but something like CONNECTION_ERROR as opposed to ERROR which we already have.

**Comment by tmontgomery** [comment]
CONNECTION_ERROR has been added as an error code to the ERROR frame. So that can be used.

**Comment by tmontgomery** [comment]
Language around, transport protocol requirements, frame validation, and handling the I bit has been added that clarify the protocol responsibility have been added.
