### ISSUE TITLE
Multiple frame metadata and data application delivery undefined

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#52]
@benjchristensen tells me that the implementation intends to hide processing of multiple frames so that the application only receives the final result of all the metadata and payload data put back together.

For payload data, which is arbitrary bytes, I assume all the data is concatenated and delivered as one big binary blob. But what about metadata? The concept of metadata in Reactive Socket itself implies some sort of meaning or encoding. (If there isn't any, then metadata should be defined as just a separate binary block for separate delivery to the app, as kind of a convenience method by which the app can get two binary blobs instead of one that it has to split into two.)

The behavior of delivery to the application needs to be defined.

**Comment by NiteshKant** [comment]
Metadata and data encoding are defined in the [SETUP frame](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#setup-frame) and the discussion between metadata as a separate frame as opposed to within the same frame with data was discussed in issues #3 and #13

**Comment by wmiaw** [comment]
MIME type behaviors are not defined in the spec. If you're going to specify this stuff inside Reactive Sockets, you need to define the behaviors.

If the metadata MIME type is audio/mpeg3 or text/plain then perhaps the metadata across multiple frames is simply concatenated together.

If the metadata MIME type is text/rfc822 then perhaps metadata across multiple frames should be last-frame-wins.

**Comment by tmontgomery** [comment]
@wmiaw I believe the easiest way to clarify this is that the (potentially reassembled) RESPONSE or request is an entire object with the MIME type. So, concat or last-object-wins is up to usage.
