### ISSUE TITLE
Is ERROR frame for application or stream errors?

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#53]
The protocol definition states an ERROR frame is used to communicate a stream ERROR from a responder to a requestor.

However, unlike the SETUP ERROR frame, there are no error codes defined. Instead it is a free-form UTF-8 encoded string. Is this really for application errors sent back instead of a RESPONSE frame? (That's what @benjchristensen says to me.) If so, application level errors probably shouldn't exist within a Reactive Socket level structure. And they could continue to use MIME type encoded data to provide an application level response that is interpreted by the application as an error.

If these are actually stream errors, like the frame send from the requester is malformed or unrecognized, then this should provide strict error semantics at the Reactive Socket level like is done for the SETUP ERROR frame.

**Comment by stevegury** [comment]
#25 now implies that we need a protocol level error message.
We can define this by either defining error code in the ERROR frame and using it for either application errors and protocol error, or define a new message type.

**Comment by tmontgomery** [comment]
We could:

- Define ERROR to be allowed on Stream ID 0.
- Remove SETUP_ERROR as a separate frame type.
- Use ERROR on Stream ID 0 to mean connection level error with connection teardown (?).

Whether seen during SETUP or during operation, ERROR on Stream ID 0 is not necessary to distinguish between. The operation is the same. Inform application, etc.

**Comment by NiteshKant** [comment]
+1 to allow ERROR frames on Stream 0 and SETUP_ERROR being just an instance of such a frame.

**Comment by stevegury** [comment]
I don't have any strong preference, I'm fine with only one type of ERROR frame.
We can then define ranges of ERROR_CODE, which may depend on the streamId (it's simpler if they don't).

**Comment by tmontgomery** [comment]
Removed SETUP_ERROR and using ERROR for all types of errors. Added ranges of error codes, etc.
