### ISSUE TITLE
Connection Establishment lease behavior reads contradictorily

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#54]
The text describing connection establishment has some contradictory statements in it, which I don't think is intended.

For example, the following two sentences contradict:
> The server-side Requester may send requests immediately upon receiving a SETUP frame that it accepts.
> If a client-side Requester sets the L flag in the SETUP frame, the server side Requester MUST wait for a LEASE frame from the client-side Responder before it can send a request.

And the client- and server-side behaviors are inconsistent even though they are both requesters:
> The client-side Requester that has set the L flag in the SETUP frame MUST wait for the server-side Responder to send a LEASE frame before it can send Requests.
> The server-side Requester may send requests immediately upon receiving a SETUP frame that it accepts.

The text-based sequences are clearer, and do not conflict knowing they are different scenarios.

**Comment by tmontgomery** [comment]
Will look and see if these could be tightened up. I'm not a fan of how organic that section has been developing. It's a bit sloppy and needs to be presented clearer. So, very valuable input here!
