### ISSUE TITLE
Behavior upon receipt of post-cancel frames undefined

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#55]
The Reactive Socket protocol definition does not define what it should do upon receipt of frames belonging to a stream ID that has already been cancelled.

**Comment by tmontgomery** [comment]
Actually it does. The "Handling the Unexpected" together with the sequences explain it. Once a stream is terminated (via a CANCEL, for example), the stream ID is no longer known. So, frames for it are ignored (unless they are request types and thus starting a new stream).

**Comment by wmiaw** [comment]
Okay. I did not see anything that says CANCEL (and I guess ERROR too?) means the stream ID is then considered unknown for the receiver.

**Comment by tmontgomery** [comment]
It mentions the stream is "terminated" by the Requester or Responder based on events. Those are in the stream sequences. The intention probably needs to be made clear, though.

**Comment by tmontgomery** [comment]
The spec has been updated to add some language for this around Stream lifetime.
