### ISSUE TITLE
Ping Behavior

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#58]
Should the protocol have built in ping functionality to allow either side to test latency and health of a connection?

See HTTP/2 Ping https://http2.github.io/http2-spec/#PING

**Comment by benjchristensen** [comment]
It is somewhat similar to KEEPALIVE except a server/responder could initiate it whenever it wants.

**Comment by NiteshKant** [comment]
I always thought that KEEPALIVE frames were bi-directional but reading the spec now it seems that only client sends the KEEPALIVE frames. I think it should be made bi-directional to make sure that the connection is healthy either ways. However, such an interaction can not measure round trip latency as can be measured with ping-pong in websockets for example & what HTTP/2 seems to be suggesting. 
Should we replace one sided keep-alive frames with a ping-pong semantic?

**Comment by stevegury** [comment]
It's unidirectional because the server can rely on the client KEEPALIVE (it already knows its period).
We discussed this previously, the decision was to use KEEPALIVE for liveness detection, and let the library on top of reactivesocket implement applicative ping if needed.

**Comment by NiteshKant** [comment]
@stevegury KEEPALIVE in one direction can only guarantee liveness in one direction on a TCP connection. Issues as described in #41 may arise if the liveness is not checked in the other direction i.e. if the connection is in a state that the data flows in only one direction (client -> server in this case) and not in the other direction.

**Comment by tmontgomery** [comment]
Currently, KEEPALIVE is used by the server to determine the client is alive. The server sending a KEEPALIVE in response to receiving a KEEPALIVE assures the client that the server is alive. So, currently, we can have liveness checks on both sides if the KEEPALIVE is echoed by the server. Which is the current intent.

RTT measurement is trickier. A client can measure easily by piggybacking data in the KEEPALIVE that the server echoes. But the server does not currently have a means to determine client RTT.

We can chat tomorrow on one-way latency measurement. There are ways to do this. Several actually. Depends on what is the desired fidelity, etc.
