### ISSUE TITLE
Do we need a version per frame?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#60]
Currently, all frames in the protocol contain a version field. Do we foresee multiple protocol version messages exchanged on the same Reactive Socket? If not, then just sending the version in the setup frame should suffice.

**Comment by stevegury** [comment]
That's a good question, I don't forsee multiple versions used at the same time on the same connection.
I'm interested in what @tmontgomery think about this issue.

**Comment by tmontgomery** [comment]
I've updated the protocol spec to remove version from every frame type, except SETUP. I think this works for the known use cases.
