### ISSUE TITLE
Protocol Impact on Implementation Efficiency

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#62]
I had discussions today that brought up questions about implementing ReactiveSocket (client) for very low powered devices (think $25 devices). I want to know if there are any design decisions in the protocol that impede very efficient implementations that have been made assuming higher-powered devices.

**Comment by NiteshKant** [comment]
Is the baseline of perf HTTP/1 i.e. are these devices currently communicating using HTTP/1?

**Comment by stevegury** [comment]
The usual limitation of those very low powered devices usually are:
- memory constraint
- cpu constraint

I don't see anything in the current design that hinder an implementation for low power devices. On the contrary, the request/stream interaction model allow low power device to process a potentially large message without having to load it entirely in memory.

**Comment by tmontgomery** [comment]
I don't believe there is anything in the protocol that would be impossible to implement very efficiently.

**Comment by wmiaw** [comment]
The following two items listed under Motivations "Scalability & Performance" are potentially incorrect in certain execution environments:

* reducing computation time by using binary encoding
* allocating less memory and reducing garbage collection cost

The use of binary encodings may actually increase computation time and require more memory allocations. Work should be done in conjunction with the Gibbon and Cadmium teams to validate these assumptions.

**Comment by tmontgomery** [comment]
The wording for the HTTPbis IETF WG charter for binary encoding might be useful. I.e. "certain aspects have been identified as hampering performance". As both these aspects are comparative, it might be clean to mention the "compared to" portion.

**Comment by benjchristensen** [comment]
We are unaware of anything that would prevent efficient implementations while still achieving our desired behavior.
