### ISSUE TITLE
Should LEASE TTL and Number of Requests be 32-bit?

### ISSUE THREAD

**Issue by tmontgomery** [ReactiveSocket/reactivesocket#65]
@stevegury we made some changes to reduce Stream ID size to 32-bits and Request N to 32-bits. Want to see if LEASE TTL and Number of Requests could also be slimmed down.

1. TTL can be changed in resolution to milliseconds and a 32-bit value would thus allow 49 days of LEASE time. A resolution of 1 second would allow for 136 years of LEASE time. A resolution of 1 microsecond would allow for only 71 mins of LEASE time.

1. Number of Requests being 32-bits allows for 4 billion requests at a time. This would seem to be fine.

If needed, we can add a bit for infinity for TTL and/or Number of Requests if needed.

Thoughts?

**Comment by stevegury** [comment]
What the motivation for reducing the size of those fields?

I don't forsee any problem with the LEASE time, I think a 32-bit value expressing a number of milliseconds is fine (49 days or 25 days if we use a java signed int). And we can use Integer.MAX_VALUE for Infinity.

Regarding the streamId, I suppose the implementation of GOAWAY will rely on the streamIds to be monotonically increasing. I don't expect to see an overflow with 64bits but that becomes more possible with 32bits. We need to be carreful in the implementation, and don't forget to close the connection when we overflow.
