### ISSUE TITLE
How are handshakes eliminated?

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#67]
Motivations "Scalability & Performance" says one of the goals is to eliminate the cost of handshakes, specifically mentioning SSL/TLS.

Other than the potential LEASE handshake optimizations described by Reactive Socket itself, I don't see how using Reactive Socket eliminates handshakes in other protocols that may be in use. Or is this bullet point better said as a goal of Reactive Socket itself: avoiding the use of handshakes for session establishment in the protocol?

**Comment by tmontgomery** [comment]
The latter is the way it should be stated. ReactiveSocket is trying to eliminate its own RTTs for session establishment (when possible). There isn't much that RS could do for other protocols it is using in this regard.
