### ISSUE TITLE
Closing Underlying Transport

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#68]
The Protocol "Handling Ignore Flag" section states an implementation may close the underlying transport if it receives a frame that it does not understand, and the ignore flag is not set.

Does a ReactiveSocket ERROR or CANCEL need to be sent first? Otherwise it seems the Reactive Socket stack needs to get notification of underlying transport connection state changes which maybe does not happen (e.g. HTTP/2 in a web browser).

**Comment by tmontgomery** [comment]
We've talked about this as well. I think it would be cleaner to send a connection level (stream ID of 0) ERROR. But we need to actually be a little more explicit around when this is appropriate and what level of cleanup must be done.

**Comment by benjchristensen** [comment]
Protocol was updated for further clarity.
