### ISSUE TITLE
Are strings null terminated?

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#69]
In various locations ASCII strings are mentioned as the data format. Are strings null-terminated or not? The string lengths (e.g. MIME length) need to account for this; it is perhaps better if they are not guaranteed to be null-terminated because then recipients will explicitly have to read as bytes instead of using a string parser which is error prone.

**Comment by tmontgomery** [comment]
The metadata and data portions are all length based. So, they don't need null termination and length is known up front. In addition, the MIME type fields are length prefixed and known up front.

So, I don't think they need to be NULL terminated nor should be guaranteed to be.
