### ISSUE TITLE
Cancel frame on stream 0

### ISSUE THREAD

**Issue by stevegury** [ReactiveSocket/reactivesocket#7]
The specification doesn't mention anything about cancelling on stream 0.
I think that we should either call out that's invalid, or specify the behavior.

I think that it should equivalent to closing the connection then making it invalid.

**Comment by tmontgomery** [comment]
Agreed. We need to actually add some statements around how to handle the unexpected. This is one. Also, Request on a live stream, etc.

**Comment by stevegury** [comment]
The behavior is now clearly specified (ignore).
