### ISSUE TITLE
No invalid frame error code

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#70]
There is an invalid_setup error code 0x0001. I don't see an invalid_frame error code. The 0x0024 invalid error code is an application level error code.

**Comment by tmontgomery** [comment]
The INVALID error code is for an invalid request. Not an invalid frame.

An invalid frame might be handled a number of ways and beyond what is now specified in "Handling the Unexpected", an invalid frame might require a closing of the underlying transport connection or might be ignored. I don't think it adds value to an implementation for an "invalid frame" error code as the protocol action is probably conditional.

**Comment by benjchristensen** [comment]
Have determined this does not need to be added to the protocol.
