### ISSUE TITLE
Error code ranges are small

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#71]
The small number of 16 error codes for setup, 16 for connection, and 16 for application are very small. Particularly for application error codes. Applications are going to run out of error codes quickly and will have to start mixing in payload-carried application error codes. And then you'll have a mix of some error codes in the ReactiveSocket error frame and some in the error frame metadata or some in a response frame payload.

I see this as becoming an issue. Even if you expand it to 65K error codes.

**Comment by tmontgomery** [comment]
I've expanded the ranges for error codes in the ERROR frame. Take a look and see if the wording and values make more sense.

In general, I think the error codes for the application should be up to the application to leverage with certain protocol specific errors reserved in the table.

**Comment by wmiaw** [comment]
Makes sense.
