### ISSUE TITLE
Extension error code unclear

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#72]
It's unclear why the 0xFFFF error code is reserved for extension use. Frame type 0xFFFF makes some sense for the extension frame, but I don't understand how the extension error code should be used to match.

**Comment by tmontgomery** [comment]
This value is now 0xFFFFFFFF instead. The intention is to reserve the value for extension later if needed.

**Comment by benjchristensen** [comment]
Protocol has been updated. Closing out. Comment back if there is further discussion needed.
