### ISSUE TITLE
Protocol lacking frame descriptions

### ISSUE THREAD

**Issue by wmiaw** [ReactiveSocket/reactivesocket#73]
It would be better to have descriptions for all the frame types. Right now only some frame types (e.g. SETUP, ERROR, LEASE) are described.

**Comment by tmontgomery** [comment]
Once we have iterated more on the error handling, we should be in a good place to tighten up descriptions in the Frame Type table. There is a real danger of locking into descriptions too early while design/spec are being iterated on and prematurely limiting our thinking.

**Comment by tmontgomery** [comment]
Descriptions added to table.
