### ISSUE TITLE
Request for Feedback from Reactive Streams Community

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#78]
Pinging folks from the Reactive Streams community to express interest in your feedback (and involvement if you like what you see).

@viktorklang @rkuhn @ktoso @drewhk @jbrisbin @maniksurtani @danarmak @pk11 @smaldini @alkemist @purplefox @mariusae @normanmaurer

Related to discussions in https://github.com/reactive-streams/reactive-streams-io/issues/1 and https://github.com/reactive-streams/reactive-streams-io/issues/8

Relevant documents for review include:

- [Motivations.md](https://github.com/ReactiveSocket/reactivesocket/blob/master/Motivations.md): Motivation for creating this protocol.
- [FAQ.md](https://github.com/ReactiveSocket/reactivesocket/blob/master/FAQ.md): Frequently Asked Questions.
- [Protocol.md](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md): The protocol definition.

Status:

- Protocol seems to mostly be "done" but is still up for modifications based on credible, objective feedback with use cases or performance considerations
- Experience implementing or productizing implementations can still cause modifications
- The [Java implementation](https://github.com/ReactiveSocket/reactivesocket-java) is mostly functional. It is not yet production worthy. We have implemented it alongside the definition of the protocol and the protocol has evolved while doing so.
- We do not yet have a TCK but would like to. 
- We would like to have an implementation in Javascript (and/or C) and show interop amongst them before we consider the protocol ready to call v1.0

**Comment by pk11** [comment]
@benjchristensen regarding the JavaScript (browser/server) implementations, is there anyone working on those actively (right now I only see two empty repos)? I am interested in contributing and would like to avoid duplicating efforts.

**Comment by benjchristensen** [comment]
@yunong has expressed interest and taken lead on JS, but not much has been happening recently. So we should ask him.

**Comment by michaelbpaulson** [comment]
@pk11 I am currently working on getting the JS version to a state of being able to run tests.  Please feel free to help in anyway.  If you would like to coordinate feel free to reach out to me via email or [twitter](https://twitter.com/_michaelpaulson)

**Comment by benjchristensen** [comment]
Closing out due to inactivity.
