### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by krisskross** [ReactiveSocket/reactivesocket#82]
Hi

ReactiveSocket is a really exciting project. The Aeron implementation is particularly interesting. I was wondering if there is any recent "behind-the-scenes" information around the project that can be shared?

Cheers,
-Kristoffer

**Comment by stevegury** [comment]
Hi Kristoffer,

I don't know exactly what you expect from "behind-the-scences" information. 
But I can tell you that we (Netflix) are migrating some services to use reactivesocket, we plan to learn from this migration and improve the design and/or the implementation.
This project is still in an ongoing development, and I expect that it will reach a relatively stable state during 2016.

In the meantime, if you want to contribute and/or be an early adopter, we would be glad to help you.

**Comment by krisskross** [comment]
Glad to hear that the project is moving along. I don't have enough time to do any real contribution at the moment but I have already started to play around with the API for a project of mine. So count me in on the early adopter list. 

Sounds like 2016 is going to be an exciting year then. I'll do my best to contribute any way I can. Keep up the good work!

**Comment by krisskross** [comment]
Oh one question. Are there SNAPSHOT repositories available for the different projects?

**Comment by stevegury** [comment]
Yes, they are in https://oss.jfrog.org/libs-snapshot

**Comment by krisskross** [comment]
Awesome, thank you!

**Comment by shafqatevo** [comment]
Hi, is this project still active somewhere in some other form or abandoned? Any other alternative to RSocket?

**Comment by yschimke** [comment]
Checkout the various language implementations.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/231923/219020614-59939799-4e67-40f9-aa05-edd82728cf8b.png">

**Comment by shafqatevo** [comment]
> Checkout the various language implementations.
> 
> <img alt="image" width="924" src="https://user-images.githubusercontent.com/231923/219020614-59939799-4e67-40f9-aa05-edd82728cf8b.png">

Thanks!
