### ISSUE TITLE
ReactiveSocket as HTTP/2 Extension?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket#84]
I want to do a thought experiment and explore what it would look like if we layered the ReactiveSocket semantics on HTTP/2 as an extension. This means binary framing alongside the H2 frames, not building on top of the insufficient public APIs exposed by implementations of the current H2 spec that only permit request/response. 

This relates to https://httpwg.github.io/specs/rfc7540.html#extensibility

The reason is that if companies have infrastructure with HTTP/2, it is far easier to extend, rather than replace. Additionally, some companies have strong reason to leverage H2 prioritization mechanisms, and PUSH_PROMISE behavior for digital assets. 

I'll dump more here as I work on this, but I wanted to mention my exploration in case anyone has thoughts on this ahead of time.

**Comment by NiteshKant** [comment]
:+1: I think it is a very viable layering for services at the edge. For internal service-to-service communication, not so much.

**Comment by tmontgomery** [comment]
RFC 7540 has all the tools to make this possible. Leveraging the existing frames of HTTP/2 would be fine and extending fine.

A one to one mapping of RS frames to HTTP/2 frames would be a start.

**Comment by stevegury** [comment]
:+1: I'm also reading about this. There isn't too much doc about it but it would definitely improve RS adoption.

**Comment by benjchristensen** [comment]
Pinging here again to gauge continued interest. I remain interested in this pursuit. 

HTTP/2 currently offers:

- multiplexed request/response streams with byte-level flow control
- stream prioritization
- stream cancellation

We wish to add behaviors from ReactiveSocket including:

- unidirectional message stream 
- bidirectional message stream
- stream events defined as => value* (error | complete)? 
- fire-and-forget (optimization of request/response)
- message oriented flow control on streams (credit based on messages controlled by application as opposed to credit based on bytes controlled by protocol impl) using request(n) semantics
- support for optional client/server resumption of stateful streams (important for mobile)

Is there any other behavior we want/need? Is anything above wrong?

**Comment by tmontgomery** [comment]
Definitely interested. I will take a stab over the weekend and early next week on what this might look like.

**Comment by tmontgomery** [comment]
One way to integrate is to define all ReactiveSocket frames as new frame types. However, this doesn't leverage existing infrastructure. So, a deeper integration is much more valuable. To that end, a true integration should attempt to leverage as much of the existing behaviors as possible. This means also adding as few new frame types as possible.

Here is a basic list of possibilities to ponder and hash through.

- adding SETTINGS parameters that include all the information in ReactiveSocket SETUP frames
- RST_STREAM frames replace the usage of ReactiveSocket ERROR frames. StreamID 0 ERROR frames use PROTOCOL_ERROR.
- stream cancellation via RST_STREAM CANCEL error code.
- PING frames replace ReactiveSocket KEEPALIVE frames.
- metadata is in HEADER frames (not a fan of this, but it can work. Need to hash this one out more). ReactiveSocket METADATA_PUSH can be thought of as a HEADER with a put.
- DATA frames used for ReactiveSocket RESPONSE frames and potentially REQUEST_FNF.
- extend HTTP/2 with new frame types:
    - RS_LEASE equivalent to ReactiveSocket LEASE
    - RS_REQUEST_N equivalent to ReactiveSocket REQUEST_N. Would ideally like to integrate with byte level flow control more, though.
    - RS_REQUEST that is used for all request types. An additional 1 byte field to be used for determining request type.
    - RS_RESUME that can be used for resuming operation semantics.
- extend HTTP/2 with new error codes to handle new errors and all ReactiveSockets errors.

**Comment by yschimke** [comment]
I like the idea of metadata being carried exposed as (key-value) headers because it allows for frameworks/applications to continue to use the request metadata (headers in HTTP, metadata in RS) for typical things like routing, access control.  It seems valuable to leverage existing infrastructure here as much as possible.

On the downside it seems to apply strong conventions and limitations e.g. many HTTP frameworks will restrict header length etc.  But I could certainly live with that.  

maybe the fallback is to allow a special header to signify that the metadata is still carried in the body e.g. a large CBOR encoded metadata payload.

**Comment by yschimke** [comment]
Did you discount the RS_REQUEST type just being new verbs for the HTTP :method.  e.g. extending GET, POST, DELETE etc, with new verbs like STREAM?

**Comment by tmontgomery** [comment]
@yschimke I went with the typical REST recommendation of NOT creating new methods. However, in the case of HTTP/2, it might fit better. But not sure how some infrastructure might react to it.

With respect to metadata, I think the use of HEADERS can work. But it would mean that metadata would be out of position in the stream. i.e. it would have to appear upfront when the HEADERS are sent. This might be OK as a limitation, though. Would like to hear some perspectives on that.

**Comment by benjchristensen** [comment]
Based on discussion in https://github.com/bidiweb/wish/issues/5, does it still make sense to pursue this?

Open questions for me are:

- can RS streams actually be matched with HTTP/2 streams (not convinced)
- can we use HTTP/2 Data frames as message boundaries (not clear if we can, as I've heard that proxies are free to combine them, but I can't find clarification yet)
- does the double framing matter?

The easiest option would be to leave ReactiveSocket as is, and just work on having standardized bidi byte streams via HTTP/2, similar to what we're doing with Proxygen where we control both ends, and what Fetch is pursuing, and we're discussing in https://github.com/bidiweb/wish/issues/5.

**Comment by benjchristensen** [comment]
We have adjusted the protocol to move streamId to the front of the frame (after optional length) so that we are free to layer ReactiveSocket on HTTP/2 streams. 

Extending HTTP/2 more than that becomes less interesting due to the complexities arising from resumption.
