### ISSUE TITLE
Design principals are missing.

### ISSUE THREAD

**Issue by michaelbpaulson** [ReactiveSocket/reactivesocket#85]
[Design Principals](https://github.com/ReactiveSocket/reactivesocket/blob/master/DesignPrinciples.md) are linked in the [terminology](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#terminology) section of the protocol, but do not seem to exist.  Is there a replacement for this document or should the link be removed from the protocol terminology?

**Comment by benjchristensen** [comment]
It should be removed. It was replaced by motivations and FAQ.
