### ISSUE TITLE
Metadata payload format?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#89]
#### Motivation

For the reason of flexibility, currently RS protocol does not specify any formats for metadata payload. This is great for flexibility but opens up a way to a wild wild west where everyone in a network call chain can potentially have different metadata formats. Typically, within any infrastructure there would be a need for some standardization of the metadata payload.

This issue intends to gather thoughts around the need for prescribing a metadata payload format.

#### Points to discuss

* Do we need to standardize the metadata payload?
* Do we need to provide a guidance on what is an optimal way of defining metadata payload?
* If we do provide a guidance;
     * What type of data are we looking for? HTTP 1/2 is key value eg.
     * Is [HTTP/2 hpack spec](https://http2.github.io/http2-spec/compression.html#) worthwhile to look at?

#### Possible outcomes

I hope to get to one of the following outcomes of this discussion:

- There is no need to be prescriptive in any way as to what the metadata payload format should be. This is the status quo.
- There is value in standardizing the metadata payload for RS and we come up with a spec. We will come up with a spec and implementation in this case.
- It may be useful to specify a default metadata payload format, which can be overridden if required by mime type negotiation as it exists today. We will come up with a default spec and implementation in this case.

**Comment by benjchristensen** [comment]
The SETUP frame supports negotiation of the MimeType (https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#setup-frame) for the Metadata. Why is that not sufficient? If a strict format is wanted between two endpoints, then a strict MimeType can be chosen.

**Comment by NiteshKant** [comment]
@benjchristensen it is true that the protocol allows for negotiation. This issue is more about reducing the re-invention that everyone has to do to arrive to an optimal metadata format. If the protocol provides "an option" which is suitable for most of the usecases, there are less things to worry about.

##### Why does this need apply for metadata and not data?

The variance in metadata formats are lesser as compared to data, which depends on the application. In general, metadata are key-value pairs (values can be binary) and it is possible to provide a way that suits most of the usecases. So, it appears to me that there is value in providing a format out of the box.

**Comment by stevegury** [comment]
I think that the protocol is flexible enough to do whatever we want.

That being said, I also agree that, most likely, most of the usage of the metadata will be key/value pairs, so it makes sense to change the default mime-type for the metadata from `UTF-8` to some *very simple* key value encoding, I do not recommend pulling a dependency on hpack.

If my understanding is correct, this proposal should only change the default mime-type + adding a serializer/deserializer for the metadata.

**Comment by NiteshKant** [comment]
>>> If my understanding is correct, this proposal should only change the default mime-type + adding a serializer/deserializer for the metadata.

If we choose to change the default for the metadata, from the protocol point of view, these are the changes I see:

- Update the default mime-type (as you said)
- Specify the default format (over-the-wire format) in the protocol spec.

From the implementation point of view, we will have to provide the serializer/deserializers as you suggested.

**Comment by robertroeser** [comment]
+1 for a default option

Most people are just going to want something simple that has keys/value because it's easy.

**Comment by benjchristensen** [comment]
I'm okay with a default with key/values.

**Comment by NiteshKant** [comment]
After discussions with @stevegury @robertroeser I have created the pull request #90 to describe the wire format for a default (overridable by user during setup) metadata mime type.

**Comment by NiteshKant** [comment]
ping @tmontgomery

**Comment by NiteshKant** [comment]
Closed via #90
