### ISSUE TITLE
Respecting the lease

### ISSUE THREAD

**Issue by stevegury** [ReactiveSocket/reactivesocket#9]
There's specific situation where a client may have all its leases "empty".
(this is kind of a pathological use case, but it could happen during/after an big outage)

The question is do we want to let the client still send traffic to the servers or not?
I tend to think that it would be better if the client just reject the request (i.e. reject the associated reuest from its upstream)
e.g. in a situation like this:

           -> C
    A -> B -> C
           -> C

if B has empty all its lease from the C, then I would propose that B reject the request from A that trigger the message to C (That rejection being retryable by A)

**Comment by NiteshKant** [comment]
This is a good point and I don't think it is pathological. I can see this as another flavor of "no healthy servers available" situation which is essentially the outage scenario you mentioned and it isn't uncommon :) 

However, I think the action of rejecting upstream request would also be determined by how important the dependency `C` is. eg: if there is a degraded state available for `C` i.e. it has a valid fallback, then it may not result in the rejection of upstream request. So, rejecting upstream requests based on one dependency may not apply to all scenarios. 

I also think that the scenario of inferring upstream request status based on downstream dependency status is out of scope for Reactive Socket and more or less an application concern. We should provide a way in which it is possible for an application to compose downstream failures to feed into upstream responses.

**Comment by tmontgomery** [comment]
In any situation where a request can not be serviced, an ERROR should be sent. That ERROR could be transient, thus allowing retry. But it's the applications decision to retry or not.

Even with the lease semantics, a Request may not be serviceable. So, ERROR is the necessary fallback.

**Comment by stevegury** [comment]
Closing this issue:
We decided that a client MUST respect a lease.
