### ISSUE TITLE
Update stream id handling in spec

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket#93]
Discussion in https://github.com/ReactiveSocket/reactivesocket/pull/92

**Comment by yschimke** [comment]
Moved from a PR as my change was a one liner and no longer appropriate.  Let me know if you would like me to make a first pass at the changes, otherwise I am happy to leave it to you.

**Comment by NiteshKant** [comment]
Thanks @yschimke. I will make the changes and file issues, will appreciate a review.

**Comment by NiteshKant** [comment]
Just an update: I haven't yet made this change as I am waiting #94 to get merged so that we can work on the next draft.

**Comment by benjchristensen** [comment]
Is the updated text sufficient? https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#stream-identifiers

Or should it have more details? For example, it does not discuss what happens when the max is hit.

**Comment by tmontgomery** [comment]
I believe the text currently is sufficient to distinguish what to do. Rollover would be implicit as long as 0 is avoided and odd/even is maintained.

**Comment by benjchristensen** [comment]
Change is made and considered sufficient, so closing this.
