### ISSUE TITLE
Add a Status for the protocol

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#94]
##### Problem

ReactiveSocket Protocol spec can not be considered stable as we still see issues like #93 which require minor tweaking or #83 which may require significant change.
If the spec is a moving document, it becomes difficult for people to implement the protocol. We need some kind of versioning of the spec, however, updating major version for every change is pretty heavy handed.

##### Proposal

I suggest the following:

- State in the spec that this is a draft which is currently at version 1 i.e. the spec is a draft-1.
- Create a branch draft-n (which is the next draft for the spec).
- When we see enough changes to the next draft, we merge it to master and create the next draft branch.
- Once we have implementations that are verified in production and we have confidence about stability, we change the status to 1.0.

##### Assumptions

All implementations will have an out-of-band agreement on which draft version are they using between network boundaries. This is not ideal but is better than today where two endpoints have no way of agreeing on which version of the spec they have implemented.

**Comment by NiteshKant** [comment]
If we agree on this approach, I can send a PR for this. I suggest not making any changes to the spec until then.

**Comment by stevegury** [comment]
I agree with all the problems you identified and about the draft-based approach you proposed (HTTP/2 used a similar approach.) If we want to easily support backward incompatible evolution we need a way to ensure that a client can talk to a server and vice-versa.

Rather than using an out-of-band agreement, why not using an in-band agreement using the version field in the SETUP_FRAME. By convention we could treat this 32bits field as a semantic version number x.y.z.t.

It is currently at `0.0.0.1`, which can be interpreted as draft 1 of version 0.0.0.
We can make evolution of the protocol and decide later when it is stable enough to bump the version to `1.0.0.0`.

**Comment by NiteshKant** [comment]
I agree we can use the 32 bit version field (currently the spec does not define anything about what a version is, so we need to fix that too.) and have minor versions. 
I am not sure whether we need a 4 field versioning scheme though. May be we can have `major.minor` each of which are 16-bit long.

**Comment by stevegury** [comment]
Indeed, 4 numbers are a little bit overkill, and it's unlikely that we'll have any `patch` release (why bumping the patch number if it's backward compatible?).
Then your proposal seems to be the best solution.

Before making any change, we should wait for our friends at Facebook to comment/agree on this.
/cc @benjchristensen @yschimke @stupaq-fb @lehecka and @tmontgomery

**Comment by yschimke** [comment]
The version is currently only sent by the client to the server. There is no way for a server to respond apart from rejecting with an ERROR frame.  For this draft, maybe this is all that needs to be said, versioning is single version take it or leave it.

But...

Potentially a server could support 3 major versions and switch its behaviour based on the client SETUP frame.  However a client that supports 3 versions would have to walk down the version list with multiple connection attempts.  Maybe the ERROR frame could include the server VERSION??? 

In SPDY for example, IIRC the client could send the versions of the spec it supported (in ALPN) and the server chose a version it also supported.

**Comment by stevegury** [comment]
The fact that a server or client can match the version of its peer is implementation specific to me. It's good if a client or a server implement a solution like that, but I wouldn't specify it.

> The version is currently only sent by the client to the server. There is no way for a server to respond apart from rejecting with an ERROR frame.

This is what I have in mind.

> For this draft, maybe this is all that needs to be said, versioning is single version take it or leave it.

My proposal here is just to give a little bit more information to this big 32bits numbers. How so? By codifying the way we interpret it. The main benefit will be able to have a 1.0 when the protocol is stable enough.

**Comment by NiteshKant** [comment]
Looks like we have some agreement on having a `major.minor` version scheme and the other changes I proposed. I will create a PR for this to get to this mode and then we can apply other changes discussed in #92 and #93

**Comment by benjchristensen** [comment]
Please wait a couple more days this week for @tmontgomery and I to catch up on things.

**Comment by tmontgomery** [comment]
For us evolving the protocol, the major/minor distinction is very good. So, for that alone, I think this works fine. But 5 years from now, does it matter? I would hope that the protocol would be stable and that changes would be infrequent. Very infrequent. And then, what would be the guidelines for a change in the major field vs. the minor field? This is a little fuzzy for me.

One possible way to give guidelines....

The following MUST hold after major version 1.  All minor versions with the same major version SHOULD be backward compatible. All major versions SHOULD be backward compatible depending on implementation choice.

Can argue SHOULD should be a MUST, SHOULD NOT, etc.

**Comment by NiteshKant** [comment]
@tmontgomery I agree that the semantics would be different after we stabilize the protocol. 

I would vote for modifying the versioning section _when_ we reach 1.0, till then we just say that all version changes are backward incompatible.

**Comment by tmontgomery** [comment]
@NiteshKant that works, I think.

**Comment by NiteshKant** [comment]
@tmontgomery great! So, should we merge the outstanding PR for this?
