### ISSUE TITLE
Frame length field and total frame length

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#95]
##### Problem

Spec defines the [frame header format](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#frame-header-format) to optionally have a frame length field. It specifies that the length of the frame includes the length of the frame length field (32 bit). 
I believe it is unnecessary to include the frame length field in the length of the frame as it is a constant and does not really add any value. 

As a comparison, HTTP/2 does not include the frame length field (and other constant fields) in the frame length. [Ref](https://tools.ietf.org/html/rfc7540#section-4.1)
##### Proposal

Exclude length of the frame field from the frame length.

**Open Question**: On the same lines, the other part of the header: frame type, flags and stream Id are also fixed, should we exclude that from the length also?
#### Result
- Consistent with other framing protocols like [HTTP/2](https://tools.ietf.org/html/rfc7540#section-4.1) and [WebSocket](https://tools.ietf.org/html/rfc6455#section-5.2)
- Implementations become a little easier. While parsing the frame, one does not need to do the math of finding the offset of the variable section of the frame, they can just incrementally parse the frame.

**Comment by tmontgomery** [comment]
I have no problem with this.

**Comment by NiteshKant** [comment]
@tmontgomery great! 
Once we settle on the Protocol Status change, I will do this for the next draft.

**Comment by benjchristensen** [comment]
This has been done in the revised protocol:

> Frame Length: (24 = max 16,777,216 bytes) Length of Frame. Excluding Framing Length Field.
