### ISSUE TITLE
Inconsistency in protocol flags

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket#98]
The definition of flags in the Protocol spec should be tightened up

Bit Field Value - it seems strongly implied (but not stated) that Ignore is the 1st bit, Metadata is the 2nd bit, and each frame specific flag is 3rd, 4th etc, in order of appearance. 

Starting from High Bits - This is contrary to HTTP/2 which starts from the low bits.

`FLAGS_I = 0b1000_0000_0000_0000`

Consistency across frame types - contrary to HTTP/2 each frame in RS has its flags tightly packed.  In HTTP/2 for example, each time END_HEADERS (0x4) is used it has the same value.  This means a single constant value for the flag, rather than needing to scope each flag with the frame type.

cc @stupaq-fb

**Comment by yschimke** [comment]
Let me know if you agree and I'll make the changes.  If you want to keep the current logic, I'll need to change reactivesocket-cpp to match this logic.

**Comment by NiteshKant** [comment]
>> it seems strongly implied (but not stated) that Ignore is the 1st bit, Metadata is the 2nd bit, 

Doesn't the [Frame Header Format section](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#frame-header-format) specify the common flags bit fields and each frame specify specific flags?

>> This means a single constant value for the flag, rather than needing to scope each flag with the frame type.

Can you explain more with an example of a flag in the spec today?

**Comment by yschimke** [comment]
@NiteshKant Yes, common flags are specified.  But the bit value for each isn't stated.  They don't even match in the two implementations we currently have.

Then something like the Follows flag which exists for two frames is coincidentally the same value

    public static final int FLAGS_RESPONSE_F = 0b0010_0000_0000_0000;
    public static final int FLAGS_REQUEST_CHANNEL_F = 0b0010_0000_0000_0000;

**Comment by tmontgomery** [comment]
I've just opened up #99 to discuss moving some things a bit. Flags falls into that.

With the header descriptions, the bit value is explicitly shown in each case in each header diagram. If one is missing, please point it out.

Going to low to high or high to low has no real impact on parsing, really. MSB to LSB has some impact for hardware implementations. But that is not the case here.

Some flags are going to be frame type specific and not exist at all in other frame types. There are many ways to handle this, but this is a fairly normal way to handle it. If we shrink the flags field down to 8 bits, then we will need to fit all flags into that area for all frame types. Or let those flags go somewhere else.

**Comment by yschimke** [comment]
I missed the encoding of flags in the diagram.  Thanks for pointing it out.  I think adding "(0x80)" to the text is still a nice aid, any objection to me adding that?  

`|0|M|L|S|       Flags           |```

My mind looked at the Flags part, that could probably say "Unused" instead to make it clearer.

If there is no change to the encoding, I'll update reactivesocket-cpp to match.

**Comment by yschimke** [comment]
assuming any changes are part of #99 mentioned above
