### ISSUE TITLE
Evolving the protocol to the next stage

### ISSUE THREAD

**Issue by tmontgomery** [ReactiveSocket/reactivesocket#99]
RS has been refined a bit over the last year and experience by @stevegury @NiteshKant and @robertroeser are invaluable. I think RS is at a stage where this experience and some background pondering/thinking/etc. has helped tremendously to identify problems, issues, etc. The protocol needs to evolve to the next stage with this experience.

For that, I have a list of suggestions I would like to discuss.
1. Move frame length and framing to its own small protocol specification, moving it out of RS Protocol.md and into Framing-Protocol.md. This entails tightening up the spec to remove framing, making the list of transports mention the framing protocol when needed (currently only with TCP), and cleaning up some of the language. This does not change the on the wire representation. It simply separates the concerns of framing into its own "mini" protocol and cleans up RS.
2. Make the frame length field 24-bits. Shrinking this down avoids bad behaviors of using very large frames that might head-of-line block, especially on lossy or congested links. 15MB (roughly) is not a small frame size to be limited to.
3. Compress down Frame Type and Flags fields to 1 byte each. When starting RS, we didn't know how many frames were needed. Now we have a decent view that it won't require 16-bits. So, shrinking down frame type seems logical. Flags also doesn't currently need 16 bits. And I can't see why it would off hand. Shrinking to 8 bits seems appropriate.
4. Allowing unaligned access on fields. The reasoning behind the sizes of the frame length, frame type, and flags fields being what they are was to allow for aligned access to fields. However, given that most usage will be on TCP (either over TCP directly, WebSocket, or some other protocol over TCP) and the fact that payloads are not padded, means that most aligned access is not going to happen except by luck. Therefore, it seems wrong to waste space. Instead, assume unaligned access and shrink fields. Hence the points above about each field size.

You might notice that with 24-bit frame length, followed by 8-bit type and 8-bit flags and a 32-bit streamId, this starts to look like HTTP/2 frames. Indeed, that would be the case.

Thoughts?

Edit: there are other suggestions I have. But this is probably the most impactful.

**Comment by NiteshKant** [comment]
👍 

For my understanding,

Do you have in mind to define concepts like `leasing`, flow control, Handling the unexpected, layering with different protocols (TCP, WebSocket, HTTP/2), etc. in the main `Protocol.md` and the frame definitions (which forms the major chunk of the protocol spec today) into a `Frames.md`? (We can bike-shed on the name of the files later I guess :) )

It will also be good to discuss Byte level flow control (Issue #83) then.

Should we be also looking at the HTTP/2 extensions for RS in this iteration?

**Comment by stevegury** [comment]
This is indeed impactful !
I think that all your suggestions make sense, the main challenge for us will be upgrading existing systems, I would love if we could batch all those changes.

**Comment by benjchristensen** [comment]
> Should we be also looking at the HTTP/2 extensions for RS in this iteration?

That is a very different beast. To me that is a separate protocol definition of the same ideas, but redone with different framing. And it only works for HTTP/2, not over TCP, Aeron, WebSockets, etc.

**Comment by tmontgomery** [comment]
@NiteshKant Correct. The goal is mainly to only talk about framing in that simple protocol. Nothing else. In fact, it should only be a very simple length pre-pended protocol. Nothing else.

We should discuss #83 as well, I think. Especially in light of adding some additional aspects like resuming operation after disconnect, which I think should be discussed.

**Comment by NiteshKant** [comment]
@benjchristensen I think one thing that will be useful if we think about HTTP/2 extension is how does ReactiveSocket layer with a protocol that already contains stream based multiplexing. It may be useful in us breaking down framing with and without stream co-relation, go away frames, etc. We may not come up with a formal extension scheme but we will know that it generally works.

**Comment by benjchristensen** [comment]
@NiteshKant I'll leave that to the expertise of @tmontgomery for providing guidance on the best way to do this.

**Comment by tmontgomery** [comment]
@NiteshKant it is worth discussing in some detail. HTTP/2 doesn't allow just general framing. Some rules do restrict some exchanges.

**Comment by tmontgomery** [comment]
Looking into extending HTTP/2 more, I have a few possible ideas how this could look. I'll put together some thoughts in a separate issues for this.

**Comment by benjchristensen** [comment]
Items discussed here have been done and merged into the protocol.
